# Builds RP7D's 2DHD Zyrex sheets from the RP7B originals (AOV-saga-new/assets/2D sprites/zyrex).
# Each RP7B sheet is 1254x1254, a 4x4 grid: rows DOWN / LEFT / RIGHT / UP, four frames each.
# Output: assets/zyrex2d/<sheet>.webp at 512x512 (128 px cells) + developer/zyrex2d-data.js (species + sheet metrics).
#   python3 tools/build_zyrex2d.py "<path to RP7B zyrex folder>"
import os, sys, json
from PIL import Image
SRC = sys.argv[1]; ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'zyrex2d'); os.makedirs(OUT, exist_ok=True)
SP = json.load(open(os.path.join(ROOT, 'tools', 'rp7b_zyrex_species.json')))
SIZE, CELL = 512, 128
def sheet(name):
    p = os.path.join(SRC, name + '.png'); o = os.path.join(OUT, name + '.webp')
    if not os.path.exists(p): return None
    if os.path.exists(o) and os.path.getsize(o) > 0: small = Image.open(o).convert('RGBA')   # already built: only re-measure
    else:
        im = Image.open(p).convert('RGBA')
        a = im.getchannel('A').point(lambda v: 0 if v < 20 else v); im.putalpha(a)
        pm = Image.composite(im, Image.new('RGBA', im.size, (0, 0, 0, 0)), a)   # clear keyed colour under transparent pixels
        small = pm.convert('RGBa').resize((SIZE, SIZE), Image.LANCZOS).convert('RGBA')
        small.save(o + '.tmp', 'WEBP', quality=88, method=4); os.replace(o + '.tmp', o)
    al = small.getchannel('A').point(lambda v: 255 if v > 40 else 0)
    rows = []
    for r in range(4):
        top, bot, lef, rig = CELL, 0, CELL, 0
        for c in range(4):
            bb = al.crop((c * CELL, r * CELL, (c + 1) * CELL, (r + 1) * CELL)).getbbox()
            if bb: lef, top, rig, bot = min(lef, bb[0]), min(top, bb[1]), max(rig, bb[2]), max(bot, bb[3])
        rows.append([round(top / CELL, 3), round(bot / CELL, 3), round(lef / CELL, 3), round(rig / CELL, 3)])  # content top / feet / left / right, as fractions of a cell
    return {'file': name + '.webp', 'rows': rows}
out = {}
for sid, d in sorted(SP.items()):
    idle = sheet(sid + '-sit') if os.path.exists(os.path.join(SRC, sid + '-sit.png')) else None
    base = sheet(sid)
    move = None
    for v in ('run', 'walk', 'fly'):
        if os.path.exists(os.path.join(SRC, f'{sid}-{v}.png')): move = sheet(f'{sid}-{v}'); move['kind'] = v; break
    if idle and base and not move: move = dict(base, kind='walk')   # a "-sit" idle: the base sheet is its walk
    idle = idle or base or move
    if not idle: print('NO ART', sid); continue
    tier = d['tier'] if d['tier'] and d['tier'] <= 10 else 5
    out[sid] = {'name': d['name'], 'tier': tier, 'type': d['type'], 'type2': d['type2'], 'moves': d['moves'], 'pop': d['pop'], 'idle': idle, 'move': move}
    print(sid, idle['file'], move and move['file'])
js = '// GENERATED by tools/build_zyrex2d.py from RP7B (species table + 2DHD sheet metrics). Do not edit by hand.\n// rows: DOWN / LEFT / RIGHT / UP · each [top, feet, left, right] of the drawn creature as fractions of its cell.\nexport const ZYREX2D = ' + json.dumps(out, separators=(',', ':')) + ';\n'
open(os.path.join(ROOT, 'developer', 'zyrex2d-data.js'), 'w').write(js)
print(len(out), 'species')
