// RP7D · the locked cave placement (cave-placement.js · hydrateLock). Generated, not hand-edited: delete the
// placements to recompute from the live world.
export const CAVE_LOCK = {
 "version": 1,
 "note": "Validated cave placement (RP7D Cave System V1.1 \u00b7 Phase F). Generated by the in-game placement against the live terrain; read by world.js. Delete to recompute.",
 "calibration": {
  "residual": 35
 },
 "settings": {
  "BUFFER": 18,
  "PAIR_MIN": 70,
  "STEP": 6,
  "FOOTPRINT": {
   "mountain": 26,
   "canyon": 24
  }
 },
 "placements": [
  {
   "id": "cave_malezor_gemlord",
   "status": "PASS",
   "pinned": true,
   "center": {
    "x": -78,
    "z": -175.8
   },
   "face": 0,
   "entrance": {
    "x": -78,
    "z": -164,
    "face": 0
   },
   "minBorder": 56,
   "clearance": -34,
   "nearestAsset": "treehouse-trail",
   "pairSeparation": 270,
   "priorWorld": {
    "x": -157,
    "z": -157
   },
   "footprintR": 26,
   "rejected": {}
  },
  {
   "id": "cave_malezor_natural",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 30,
    "z": 72
   },
   "face": -2.55359,
   "entrance": {
    "x": 20.415,
    "z": 57.622,
    "face": -2.554
   },
   "minBorder": 151,
   "clearance": 16,
   "nearestAsset": "river",
   "pairSeparation": 270,
   "priorWorld": {
    "x": 126,
    "z": 86
   },
   "footprintR": 24,
   "rejected": {
    "too near its district border": 140,
    "protected asset": 2549,
    "too near its pair": 14,
    "too near Zarvane": 998,
    "water": 393
   }
  },
  {
   "id": "cave_zarvane_gemlord",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 6,
    "z": 456
   },
   "face": 2.31274,
   "entrance": {
    "x": 18.738,
    "z": 444.323,
    "face": 2.313
   },
   "minBorder": 119,
   "clearance": 70,
   "nearestAsset": "moriPatrols:mori-western-ridge",
   "pairSeparation": 168,
   "priorWorld": {
    "x": -56,
    "z": 427
   },
   "footprintR": 24,
   "rejected": {
    "protected asset": 1049,
    "too near its district border": 65,
    "too near Malezor": 1003,
    "too near Andrannor": 609
   }
  },
  {
   "id": "cave_zarvane_natural",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 174,
    "z": 468
   },
   "face": -2.51757,
   "entrance": {
    "x": 163.903,
    "z": 453.977,
    "face": -2.518
   },
   "minBorder": 121,
   "clearance": 43,
   "nearestAsset": "zarvane-hub-road",
   "pairSeparation": 168,
   "priorWorld": {
    "x": 213,
    "z": 498
   },
   "footprintR": 24,
   "rejected": {
    "protected asset": 1049,
    "too near its district border": 65,
    "too near Malezor": 1003,
    "too near its pair": 429,
    "too near Andrannor": 609
   }
  },
  {
   "id": "cave_andrannor_gemlord",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 474,
    "z": 390
   },
   "face": 0.44118,
   "entrance": {
    "x": 481.994,
    "z": 406.928,
    "face": 0.441
   },
   "minBorder": 113,
   "clearance": 21,
   "nearestAsset": "moriPatrols:mori-northern-flats",
   "pairSeparation": 159,
   "priorWorld": {
    "x": 462,
    "z": 320
   },
   "footprintR": 26,
   "rejected": {
    "too near Zarvane": 632,
    "too near its district border": 90,
    "protected asset": 904,
    "too near Netharion": 456,
    "too near Veridan": 231
   }
  },
  {
   "id": "cave_andrannor_natural",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 552,
    "z": 528
   },
   "face": -2.55359,
   "entrance": {
    "x": 542.415,
    "z": 513.622,
    "face": -2.554
   },
   "minBorder": 113,
   "clearance": 22,
   "nearestAsset": "andrannor-hub-road",
   "pairSeparation": 159,
   "priorWorld": {
    "x": 587,
    "z": 560
   },
   "footprintR": 24,
   "rejected": {
    "too near Zarvane": 626,
    "too near its district border": 81,
    "too near its pair": 231,
    "protected asset": 876,
    "too near Netharion": 450,
    "too near Veridan": 239
   }
  },
  {
   "id": "cave_veridan_gemlord",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 846,
    "z": 264
   },
   "face": 0.89268,
   "entrance": {
    "x": 860.578,
    "z": 275.744,
    "face": 0.893
   },
   "minBorder": 112,
   "clearance": 36,
   "nearestAsset": "spawn",
   "pairSeparation": 181,
   "priorWorld": {
    "x": 815,
    "z": 231
   },
   "footprintR": 26,
   "rejected": {
    "too near its district border": 80,
    "too near Andrannor": 279,
    "protected asset": 1196,
    "too near Netharion": 124,
    "leaves its district": 13
   }
  },
  {
   "id": "cave_veridan_natural",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 996,
    "z": 366
   },
   "face": -2.0844,
   "entrance": {
    "x": 979.695,
    "z": 356.802,
    "face": -2.084
   },
   "minBorder": 121,
   "clearance": 34,
   "nearestAsset": "spawn",
   "pairSeparation": 181,
   "priorWorld": {
    "x": 1013,
    "z": 443
   },
   "footprintR": 26,
   "rejected": {
    "too near its district border": 80,
    "too near Andrannor": 279,
    "protected asset": 1196,
    "too near its pair": 332,
    "too near Netharion": 124,
    "leaves its district": 13
   }
  },
  {
   "id": "cave_netharion_gemlord",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 858,
    "z": 660
   },
   "face": -1.26629,
   "entrance": {
    "x": 841.515,
    "z": 665.181,
    "face": -1.266
   },
   "minBorder": 120,
   "clearance": 18,
   "nearestAsset": "seerPatrols:tower-watch",
   "pairSeparation": 132,
   "priorWorld": {
    "x": 779,
    "z": 609
   },
   "footprintR": 24,
   "rejected": {
    "too near Andrannor": 437,
    "too near Vorashil": 66,
    "protected asset": 858,
    "too near its district border": 51,
    "too near Veridan": 149
   }
  },
  {
   "id": "cave_netharion_natural",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 768,
    "z": 756
   },
   "face": 2.87763,
   "entrance": {
    "x": 772.509,
    "z": 739.319,
    "face": 2.878
   },
   "minBorder": 117,
   "clearance": 11,
   "nearestAsset": "netharion-hub-road",
   "pairSeparation": 132,
   "priorWorld": {
    "x": 885,
    "z": 797
   },
   "footprintR": 24,
   "rejected": {
    "too near Andrannor": 437,
    "too near Vorashil": 66,
    "protected asset": 858,
    "too near its district border": 51,
    "too near Veridan": 149,
    "too near its pair": 229
   }
  },
  {
   "id": "cave_vorashil_gemlord",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 468,
    "z": 840
   },
   "face": 0.13801,
   "entrance": {
    "x": 470.575,
    "z": 858.542,
    "face": 0.138
   },
   "minBorder": 112,
   "clearance": 17,
   "nearestAsset": "spawn",
   "pairSeparation": 180,
   "priorWorld": {
    "x": 383,
    "z": 820
   },
   "footprintR": 26,
   "rejected": {
    "protected asset": 706,
    "too near its district border": 58,
    "too near Xilnar": 503,
    "too near Netharion": 98
   }
  },
  {
   "id": "cave_vorashil_natural",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 474,
    "z": 1020
   },
   "face": 3.10457,
   "entrance": {
    "x": 474.693,
    "z": 1001.293,
    "face": 3.105
   },
   "minBorder": 69,
   "clearance": 41,
   "nearestAsset": "vorashil-hub-road",
   "pairSeparation": 180,
   "priorWorld": {
    "x": 568,
    "z": 967
   },
   "footprintR": 26,
   "rejected": {
    "protected asset": 706,
    "too near its district border": 58,
    "too near its pair": 233,
    "too near Xilnar": 503,
    "too near Netharion": 98
   }
  },
  {
   "id": "cave_xilnar_gemlord",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 648,
    "z": 1176
   },
   "face": 2.22787,
   "entrance": {
    "x": 662.822,
    "z": 1164.566,
    "face": 2.228
   },
   "minBorder": 96,
   "clearance": 32,
   "nearestAsset": "spawn",
   "pairSeparation": 161,
   "priorWorld": {
    "x": 643,
    "z": 1145
   },
   "footprintR": 26,
   "rejected": {
    "too near Vorashil": 355,
    "protected asset": 530,
    "too near its district border": 22,
    "too near Baelgor": 709
   }
  },
  {
   "id": "cave_xilnar_natural",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 762,
    "z": 1062
   },
   "face": -0.63275,
   "entrance": {
    "x": 750.93,
    "z": 1077.096,
    "face": -0.633
   },
   "minBorder": 86,
   "clearance": 14,
   "nearestAsset": "xilnar-hub-road",
   "pairSeparation": 161,
   "priorWorld": {
    "x": 808,
    "z": 1042
   },
   "footprintR": 26,
   "rejected": {
    "too near Vorashil": 355,
    "protected asset": 530,
    "too near its district border": 22,
    "too near its pair": 257,
    "too near Baelgor": 709
   }
  },
  {
   "id": "cave_baelgor_gemlord",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 1050,
    "z": 1056
   },
   "face": -0.32175,
   "entrance": {
    "x": 1044.08,
    "z": 1073.759,
    "face": -0.322
   },
   "minBorder": 114,
   "clearance": 14,
   "nearestAsset": "spawn",
   "pairSeparation": 139,
   "priorWorld": {
    "x": 954,
    "z": 995
   },
   "footprintR": 26,
   "rejected": {
    "too near Xilnar": 735,
    "too near its district border": 77,
    "protected asset": 564,
    "too near Thardin": 833
   }
  },
  {
   "id": "cave_baelgor_natural",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 1068,
    "z": 1194
   },
   "face": -2.63449,
   "entrance": {
    "x": 1059.608,
    "z": 1178.895,
    "face": -2.634
   },
   "minBorder": 119,
   "clearance": 22,
   "nearestAsset": "moriPatrols:mori-southern-flats",
   "pairSeparation": 139,
   "priorWorld": {
    "x": 1107,
    "z": 1209
   },
   "footprintR": 24,
   "rejected": {
    "too near Xilnar": 730,
    "too near its district border": 72,
    "protected asset": 539,
    "too near its pair": 94,
    "too near Thardin": 829
   }
  },
  {
   "id": "cave_thardin_gemlord",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 1302,
    "z": 1056
   },
   "face": 0.49935,
   "entrance": {
    "x": 1310.964,
    "z": 1072.434,
    "face": 0.499
   },
   "minBorder": 119,
   "clearance": 19,
   "nearestAsset": "spawn",
   "pairSeparation": 114,
   "priorWorld": {
    "x": 1263,
    "z": 1000
   },
   "footprintR": 26,
   "rejected": {
    "too near Baelgor": 791,
    "too near its district border": 59,
    "protected asset": 446,
    "too near Korathen": 844
   }
  },
  {
   "id": "cave_thardin_natural",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 1296,
    "z": 1170
   },
   "face": 2.42276,
   "entrance": {
    "x": 1307.379,
    "z": 1156.995,
    "face": 2.423
   },
   "minBorder": 118,
   "clearance": 10,
   "nearestAsset": "spawn",
   "pairSeparation": 114,
   "priorWorld": {
    "x": 1387,
    "z": 1232
   },
   "footprintR": 24,
   "rejected": {
    "too near Baelgor": 791,
    "too near its district border": 39,
    "protected asset": 457,
    "too near its pair": 69,
    "too near Korathen": 833
   }
  },
  {
   "id": "cave_korathen_gemlord",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 1602,
    "z": 1062
   },
   "face": 0.83298,
   "entrance": {
    "x": 1615.852,
    "z": 1074.592,
    "face": 0.833
   },
   "minBorder": 121,
   "clearance": 33,
   "nearestAsset": "spawn",
   "pairSeparation": 171,
   "priorWorld": {
    "x": 1558,
    "z": 1025
   },
   "footprintR": 26,
   "rejected": {
    "too near Thardin": 827,
    "too near its district border": 135,
    "protected asset": 1247
   }
  },
  {
   "id": "cave_korathen_natural",
   "status": "PASS",
   "pinned": false,
   "center": {
    "x": 1710,
    "z": 1194
   },
   "face": -2.61352,
   "entrance": {
    "x": 1700.568,
    "z": 1177.83,
    "face": -2.614
   },
   "minBorder": 117,
   "clearance": 23,
   "nearestAsset": "korathen-hub-road",
   "pairSeparation": 171,
   "priorWorld": {
    "x": 1743,
    "z": 1256
   },
   "footprintR": 26,
   "rejected": {
    "too near Thardin": 827,
    "too near its district border": 135,
    "too near its pair": 148,
    "protected asset": 1247
   }
  }
 ]
};
