import { RP_GAME_LIBRARY } from './n3000-library.js';
import { createHTMLAdapter } from './n3000-adapter.js';
import rp1 from './assets/n3000/rp1/package.js';
const PACKAGES = { RP1: rp1 };
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const META_KEY='rp7d.n3000.metadata.v1';
const CSS=`
.n3000-overlay{position:fixed;inset:0;z-index:220;display:grid;place-items:center;background:#030811de;color:#e8effa;font:15px/1.5 system-ui,sans-serif;backdrop-filter:blur(5px)}
.n3000-shell{width:min(1080px,94vw);height:min(780px,92vh);display:flex;flex-direction:column;border:2px solid #c9a463;border-radius:22px;background:radial-gradient(ellipse at 70% 10%,#173753,#071122 65%);box-shadow:0 0 0 5px #101a27,0 0 60px #11182d;overflow:hidden}
.n3000-header,.n3000-footer{display:flex;gap:18px;align-items:center;justify-content:space-between;padding:16px 24px;border-bottom:1px solid #33576d}
.n3000-header strong{font:24px Georgia,serif;letter-spacing:4px;color:#edcd88}.n3000-footer{border-bottom:0;border-top:1px solid #33576d;font-size:12px;color:#b2c8dd}
.n3000-body{flex:1;overflow:auto;padding:24px;min-height:0}.n3000-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}
.n3000-overlay button{font:inherit;color:inherit;border:1px solid #657385;background:#0b1c2e;padding:12px 20px;border-radius:8px;cursor:pointer}.n3000-overlay button:hover,.n3000-overlay button:focus{outline:2px solid #58d8ff;border-color:#eacb83;background:#15344b}
.n3000-overlay button:disabled{opacity:.5;cursor:default}.n3000-card{text-align:left;min-height:150px;display:flex;flex-direction:column;justify-content:end;background:radial-gradient(ellipse at 70% 35%,#1871aa80,#10152c 70%)!important}.n3000-card b{font-size:30px;color:#dbb773}.n3000-card small{font-size:11px;color:#a6bdd5}.n3000-detail{max-width:720px;margin:auto}.n3000-detail h1{font:32px Georgia,serif;color:#efd49c}.n3000-detail p{margin:18px 0}.n3000-note{border-left:3px solid #c9a463;padding:12px;background:#14233a}.n3000-home{max-width:600px;margin:40px auto}.n3000-home h1{font:42px Georgia,serif;color:#f0d392}.n3000-home button{display:block;width:100%;margin:20px 0}
.n3000-stage{position:relative;flex:1;background:#000;min-height:0;display:grid;place-items:center}.n3000-guest{border:0;display:block;width:100%;height:100%;background:#000}.n3000-overlay.play .n3000-shell{width:100vw;height:100vh;border-radius:0}.n3000-overlay.play .n3000-header{padding:7px 18px;font-size:12px}.n3000-overlay.play .n3000-header strong{font-size:18px}.n3000-overlay.play .n3000-footer{padding:6px 18px}
.n3000-status{padding:8px 18px;font-size:12px;color:#ffd893;background:#142139}.n3000-modal{position:absolute;inset:0;background:#050811dc;display:grid;place-items:center;z-index:4}.n3000-modal>div{max-width:550px;margin:20px;padding:30px;border:1px solid #d6b673;border-radius:15px;background:#112139}.n3000-modal h2{font:26px Georgia,serif}.n3000-modal button{margin:8px}
@media(max-width:600px){.n3000-grid{gap:8px}.n3000-card{padding:8px!important;min-height:125px;font-size:12px}.n3000-body{padding:12px}.n3000-header{padding:10px}.n3000-footer{font-size:10px}}
`;
export function createN3000({ onOpen, onClose, audioProfile }) {
  const style=document.createElement('style');style.textContent=CSS;document.head.appendChild(style);
  let root=null, state='closed', selected=null, adapter=null, timeout=null, generation=0, playSeconds=0, launchAt=0, confirm=false, exiting=false, hold=0, padPrev=[], axis=0, padWas=false, padKnown=false;
  let metadata={};try{metadata=JSON.parse(localStorage.getItem(META_KEY)||'{}');}catch{}
  function footer(){return '← ↑ ↓ → / left stick · Enter / ✕ select · Esc / ○ back · F10 or hold Options to return from a game';}
  function shell(body){root.classList.remove('play');root.innerHTML=`<section class="n3000-shell" aria-label="N3000 game system"><header class="n3000-header"><strong>✦ N3000</strong><span>ZYLINK · LOCAL GAME LIBRARY</span><button data-action="close">Exit system</button></header><div class="n3000-body">${body}</div><footer class="n3000-footer">${footer()}</footer></section>`;bind();focusFirst();}
  function focusFirst(){root.querySelector('button[data-primary]')?.focus();}
  function bind(){root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id));}
  function home(){state='home';shell('<div class="n3000-home"><h1>Your game system.</h1><p>Play the original RP titles through N3000. Rizer’s world waits while you play.</p><button data-action="library" data-primary>GAME LIBRARY · RP1–RP9</button><button data-action="close">RETURN TO RIZER</button></div>');}
  function library(message=''){state='library';shell(`<h2>RP GAME LIBRARY</h2>${message?`<p class="n3000-note">${esc(message)}</p>`:''}<div class="n3000-grid">${RP_GAME_LIBRARY.map(g=>`<button class="n3000-card" data-action="detail" data-id="${g.id}" ${g.id==='RP1'?'data-primary':''}><b>${g.id}</b><span>${esc(g.title)}</span><small>${g.enabled?'AVAILABLE':'ADAPTER PENDING'}</small></button>`).join('')}</div><p><button data-action="home">Back to N3000</button></p>`);}
  function detail(id){selected=RP_GAME_LIBRARY.find(g=>g.id===id);if(!selected)return library('RP GAME PACKAGE NOT FOUND');state='detail';const m=metadata[id];shell(`<div class="n3000-detail"><small>${selected.id} · ${selected.runtimeType}</small><h1>${esc(selected.title)}</h1><p>${esc(selected.description)}</p><p>${esc(selected.saveProfile.description)}</p>${m?`<p>Last played: ${esc(new Date(m.lastPlayed).toLocaleString())}<br>Play time: ${Math.floor((m.seconds||0)/60)} min · Launches: ${m.launches||0}</p>`:'<p>Not played on this N3000 yet.</p>'}<p class="n3000-note">${esc(selected.warning)}</p><p>${esc(selected.inputProfile.description)}</p><button data-action="play" data-primary ${selected.enabled?'':'disabled'}>PLAY</button> <button data-action="library">Back to library</button></div>`);}
  function status(message){const el=root?.querySelector('.n3000-status');if(el)el.textContent=message;}
  function fatal(message){if(!root)return;clearTimeout(timeout);adapter?.pause();state='error';const stage=root.querySelector('.n3000-stage');if(stage){stage.querySelector('.n3000-modal')?.remove();const modal=document.createElement('div');modal.className='n3000-modal';modal.innerHTML=`<div><h2>${selected?.id||'GAME'} COULD NOT BE STARTED</h2><p>${esc(message)}</p><button data-action="leave" data-primary>RETURN TO LIBRARY</button></div>`;stage.appendChild(modal);bind();focusFirst();}else library(message);}
  function recordLaunch(){launchAt=performance.now();playSeconds=0;const m=metadata[selected.id]||{seconds:0,launches:0};m.launches++;m.lastPlayed=Date.now();metadata[selected.id]=m;saveMetadata();}
  function saveMetadata(){try{localStorage.setItem(META_KEY,JSON.stringify(metadata));}catch{status('N3000 play history could not be saved. Guest storage is separate.');}}
  function start(){
    if(!selected?.enabled)return library('RP GAME PACKAGE NOT FOUND · title not enabled');
    const html=PACKAGES[selected.id];if(!html)return library('RP GAME PACKAGE NOT FOUND');
    state='loading';confirm=false;exiting=false;const version=++generation;root.classList.add('play');root.innerHTML=`<section class="n3000-shell"><header class="n3000-header"><strong>✦ N3000 · ${selected.id}</strong><span>${esc(selected.title)}</span><button data-action="exit">Return to library</button></header><div class="n3000-status">INITIALIZING ${selected.id}…</div><div class="n3000-stage"></div><footer class="n3000-footer">F10 / hold Esc / hold Options · return to N3000 · ${esc(selected.inputProfile.description)}</footer></section>`;bind();
    try{
      adapter=createHTMLAdapter({html,parent:root.querySelector('.n3000-stage'),game:selected,audio:audioProfile(),onEvent(type,m){if(version!==generation)return;if(type==='READY'){if(state!=='loading')return;clearTimeout(timeout);state='running';recordLaunch();status(selected.warning);if(document.hidden||confirm)adapter.pause();else adapter.focus();}else if(type==='EXIT_REQUEST')requestExit();else if(type==='ERROR')fatal(m.message);else status(m.message);}});
      // A fixed aspect guest is fitted, never stretched. RP1's canvas is natively responsive.
      if(selected.aspectRatio){const fit=()=>{const stage=root?.querySelector('.n3000-stage');if(!stage||!adapter)return;const w=stage.clientWidth,h=stage.clientHeight,r=selected.aspectRatio;adapter.iframe.style.width=`${Math.min(w,h*r)}px`;adapter.iframe.style.height=`${Math.min(h,w/r)}px`;};fit();}
      adapter.mount();adapter.start();timeout=setTimeout(()=>{if(version===generation&&state==='loading')fatal('The guest did not initialize. Return to the library and try again.');},12000);
    }catch(e){fatal(e.message);}
  }
  function requestExit(){if(!adapter || confirm || exiting)return;if(state==='error')return leave();confirm=true;adapter.pause();adapter.blur();const modal=document.createElement('div');modal.className='n3000-modal';modal.innerHTML='<div><h2>RETURN TO N3000?</h2><p>Your local scores and preferences will be saved. RP1 does not save an unfinished run.</p><button data-action="leave" data-primary>YES · RETURN TO LIBRARY</button><button data-action="resume">NO · KEEP PLAYING</button></div>';root.querySelector('.n3000-stage').appendChild(modal);bind();focusFirst();}
  function resume(){root.querySelector('.n3000-modal')?.remove();confirm=false;adapter?.resume();adapter?.focus();}
  async function leave(){if(exiting)return;exiting=true;clearTimeout(timeout);++generation;status('Saving guest data…');let ok=true;if(adapter){ok=await adapter.exit();adapter.destroy();adapter=null;}if(launchAt&&selected){metadata[selected.id].seconds+=playSeconds;saveMetadata();}launchAt=0;confirm=false;exiting=false;if(root)library(ok?'':'Guest save could not be confirmed. Existing saved data was retained.');}
  function close(){if(adapter)return requestExit();root?.remove();root=null;state='closed';hold=0;padPrev=[];onClose();}
  function action(kind,id){if(exiting)return;({home,library,detail:()=>detail(id),play:start,close,exit:requestExit,leave,resume})[kind]?.();}
  function buttons(){return [...(root?.querySelectorAll('button:not(:disabled)')||[])].filter(b=>!confirm||b.closest('.n3000-modal'));}
  function move(dx,dy){const list=buttons();let i=list.indexOf(document.activeElement);const cols=state==='library'&&!confirm?3:1;i=Math.max(0,i);list[Math.max(0,Math.min(list.length-1,i+dx+dy*cols))]?.focus();}
  function key(e){if(!root)return;const c=e.code;if(c==='F10'){requestExit();return;}if((state==='running'||state==='loading')&&!confirm)return;if(c==='Enter'||c==='Space'){if(!e.repeat)document.activeElement?.click();}else if(c==='Escape'){if(confirm)resume();else if(state==='detail')library();else if(state==='library')home();else if(state==='home')close();else if(state==='error')leave();}else if(/^Arrow/.test(c))move(c==='ArrowRight'?1:c==='ArrowLeft'?-1:0,c==='ArrowDown'?1:c==='ArrowUp'?-1:0);}
  function update(dt){if(!root)return;if(state==='running'&&!confirm&&!exiting&&!document.hidden)playSeconds+=dt;const all=[...(navigator.getGamepads?.()||[])],pad=all.find(Boolean);const down=i=>!!pad?.buttons[i]?.pressed,edge=i=>down(i)&&!padPrev[i];if(padKnown&&padWas&&!pad)status('Controller disconnected. Keyboard and Return to Library remain available.');padKnown=true;padWas=!!pad;
    if(adapter){const snapshots=all.map(p=>p?{id:p.id,index:p.index,connected:p.connected,mapping:p.mapping,timestamp:performance.now(),axes:[...p.axes],buttons:p.buttons.map((b,i)=>({pressed:i===9?false:b.pressed,touched:i===9?false:b.touched,value:i===9?0:b.value}))}:null);adapter.input(snapshots);hold=down(9)?hold+dt:0;if(hold>=.9){hold=-999;requestExit();}if(!down(9))hold=0;}
    if(!adapter||confirm||state==='error'){const x=pad?.axes[0]||0,y=pad?.axes[1]||0,dir=Math.abs(x)>.6?(x>0?1:-1):Math.abs(y)>.6?(y>0?2:-2):0;if(dir&&dir!==axis)move(Math.abs(dir)===1?Math.sign(dir):0,Math.abs(dir)===2?Math.sign(dir):0);axis=dir;if(edge(12))move(0,-1);if(edge(13))move(0,1);if(edge(14))move(-1,0);if(edge(15))move(1,0);if(edge(0))document.activeElement?.click();if(edge(1))key({code:'Escape'});}
    padPrev=pad?.buttons.map(b=>b.pressed)||[];
  }
  document.addEventListener('visibilitychange',()=>{if(adapter){if(document.hidden)adapter.pause();else if(!confirm&&state==='running'){adapter.resume();adapter.focus();}}});
  return {get isOpen(){return !!root;},get state(){return state;},get activeGame(){return adapter?selected?.id:null;},get guest(){return adapter;},library:RP_GAME_LIBRARY,key,update,open(){if(root)return;onOpen();root=document.createElement('div');root.className='n3000-overlay';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');document.body.appendChild(root);padPrev=[...(navigator.getGamepads?.()||[])].find(Boolean)?.buttons.map(b=>b.pressed)||[];home();},close};
}
