// ★ 2026-10-07 · THE LIVING MASTER CODEX · NATIVE ART
//
// Every picture in the game is defined here as pixel data: a grid of letters
// and a palette. Nothing is a PNG. Change a letter or a colour and the game
// redraws. The Art Studio (/explorer/studio.html) edits these visually and
// exports a replacement entry to paste back into this file.
//
//   rows: one string per pixel row. '.' is transparent; every other letter is
//         a colour from PALETTE (or from the sprite's own `pal`).
//   sym:  rows hold the LEFT half only; the right half is its mirror.
//   ANIM: which sprites make up each character's walk frames. "|flip" mirrors.
(function(){
  'use strict';
  var PALETTE = {"k": "#1c1626", "w": "#f4efe0", "W": "#cfc8b4", "n": "#8a8270", "N": "#4e4a40", "g": "#5fa845", "G": "#86c95a", "h": "#3f7c33", "H": "#2c5a26", "f": "#e86a8a", "F": "#ffe27a", "b": "#7a4f2c", "B": "#a87443", "u": "#4b2e1a", "p": "#c9a46a", "P": "#a8834c", "a": "#3a74d8", "A": "#8cc0f6", "z": "#24508f", "v": "#7a4bb0", "V": "#b88ae8", "c": "#3fa0e0", "C": "#a8e8ff", "r": "#c8402c", "R": "#ff8a3a", "y": "#e8b830", "Y": "#ffe08a", "o": "#c8843c", "O": "#eaa860", "s": "#b3a982", "S": "#d8cfa8", "d": "#6e6450", "e": "#9fd2e6", "E": "#dff4fb", "m": "#d9dde0", "M": "#9aa2a8", "l": "#2c2236", "L": "#4a3a52", "t": "#e8c8a8", "T": "#c49a78", "i": "#26364a", "I": "#40587a", "j": "#9db8d4", "q": "#4f8a2a", "Q": "#8ac83a", "x": "#2a4a18"};

  var SPRITES = {
    grass: { group:"tiles",
      rows:["gggggggggGgggggg",
      "gggggggggggggggg",
      "gggghggggggGgggg",
      "gggggggggggggggg",
      "gggggggggggggggg",
      "gggGggggggggghgg",
      "ggggggggggggGggg",
      "GggggggGgggggggG",
      "ggggggggggggggGg",
      "gggggghgggggghhg",
      "gggGgggggggggggg",
      "gghhgggggggggggg",
      "gggggggggggggggg",
      "ggggggggggggGggg",
      "ggggggggggghhggg",
      "gggGgggggggggggg"] },
    grass2: { group:"tiles",
      rows:["ggggggghgggggggg",
      "ghggggGggggggggg",
      "gGggggggggghgggg",
      "hhgggggGgggggggg",
      "gggggggggggggggg",
      "gGggghggggGGgggg",
      "ggggggggGggggggg",
      "gggggggggggggggg",
      "gggghgggggggggGg",
      "ggggggggggggghhg",
      "gggggggggggggggg",
      "GggggggggggGGGGG",
      "gggggGggggGggggg",
      "ggggggggghgggggg",
      "gggggggggggggggg",
      "ggggggGhhggggghg"] },
    flowers: { group:"tiles",
      rows:["ggggggggghgggggg",
      "gggfgggggggggggg",
      "ggfFfggggggggggg",
      "gggfgggggggGgggg",
      "ggggggghgghhGggg",
      "ggGgggggggghhggg",
      "ghhggggggggggggg",
      "gggggggggggwgggg",
      "ggggggggggwFwggg",
      "gggggggggggwgggg",
      "ggggggfggggggggg",
      "gggggfFfgggggggg",
      "ggggGgfggggggggh",
      "ggghhggggggggggg",
      "ggggggggggggGggg",
      "gggggghgggghhggg"] },
    path: { group:"tiles",
      rows:["ppppppPppPpppppp",
      "ppBppppppppppppp",
      "ppPppppppppppppp",
      "pppppPppppPppppp",
      "pppppppppppppppp",
      "pppppppPPpppppPp",
      "ppppPpppPBpppBpp",
      "pppppppppppppppp",
      "pppppppPpPpppppP",
      "pppppppPpPppPBpp",
      "ppBPpppppppppPpp",
      "pppppppPpppppppp",
      "pppppppppppppppp",
      "pppppppppppppppp",
      "pppppppppppppppp",
      "ppppppppPpppPppp"] },
    water: { group:"tiles",
      rows:["AAAaaaaaaaaaaaaa",
      "aaaaaaaazaaaaaaa",
      "aaaaaaaaaaaaaaaa",
      "aaaaaaazaaaaaaaa",
      "aaaaAAAaaaaaaaaz",
      "aaaaaazaaaaaaaaa",
      "aaaaaaaaaaaaaaza",
      "aaaaazaaaaaaaaaa",
      "aaaaaaaaAAAaazaa",
      "aaaazaaaaaaaaaaa",
      "aaaaaaaaaaaazaaa",
      "aaazaaaaaaaaaaaa",
      "aaaaaaaaaaazAAAa",
      "aazaaaaaaaaaaaaa",
      "aaaaaaaaaazaaaaa",
      "azaaaaaaaaaaaaaa"] },
    water1: { group:"tiles",
      rows:["aaaaaazaaaaaaaaa",
      "aaaaaaaaaaaaaaza",
      "aaaaazAAAaaaaaaa",
      "aaaaaaaaaaaaazaa",
      "aaaazaaaaaaaaaaa",
      "aaaaaaaaaaaazaaa",
      "aaazaaaaaaAAAaaa",
      "aaaaaaaaaaazaaaa",
      "aazaaaaaaaaaaaaa",
      "aaaaaaaaaazaaaaa",
      "AzaaaaaaaaaaaaAA",
      "aaaaaaaaazaaaaaa",
      "zaaaaaaaaaaaaaaa",
      "aaaaaaaazaaaaaaa",
      "aaAAAaaaaaaaaaaa",
      "aaaaaaazaaaaaaaa"] },
    den: { group:"tiles",
      rows:["bBBBBBBBBBBbBpBu",
      "BBBBBpBBBbBBBBBu",
      "BBBBBBBbBBpBBBBu",
      "BBpBBbBBBBBBBBBu",
      "BBBbBBBpBBBBBBbu",
      "BbBBBBBBBBBBbBBu",
      "BBBBpBBBBBbBBBBu",
      "uuuuuuuuuuuuuuuu",
      "BpBBBBbuBBBBBBpB",
      "BBBBbBpuBBBBBBBb",
      "BBbBBBBuBBBpBbBB",
      "bBBpBBBuBBBbBBBB",
      "BBBBBBBupbBBBBBB",
      "pBBBBBBuBBBBBpBB",
      "BBBBBbBuBBBBBBBB",
      "uuuuuuuuuuuuuuuu"] },
    rock: { group:"tiles",
      rows:["WnnWnnWnnWnnWnnW",
      "nnWnnWnnWnnWnnWn",
      "kkkkkkkkkkkkkkkk",
      "LLlLLLLLLlLLLLLL",
      "LLLLLlLLLLLLlLLL",
      "LlLLLLLLlLLLLLLl",
      "LLLLlLLLLLLlLLLL",
      "lLLLLLLlLLLLLLlL",
      "LLLlLLLLLLlLLLLL",
      "LLLLLLlLLLLLLlLL",
      "LLlLLLLLLlLLLLLL",
      "LLLLLlLLLLLLlLLL",
      "LlLLLLLLlLLLLLLl",
      "LLLLlLLLLLLlLLLL",
      "lLLLLLLlLLLLLLlL",
      "llllllllllllllll"] },
    cave: { group:"tiles",
      rows:["LLLLLLLLLLLLLLLL",
      "LLLLkkkkkkkkLLLL",
      "LLLklllllllllkLL",
      "LLkllllllllllkLL",
      "LklllllllllllkLL",
      "LkllllllllllllkL",
      "kllllllllllllllk",
      "kllllllllllllllk",
      "kllllllllllllllk",
      "kllllllllllllllk",
      "kllllllllllllllk",
      "kllllllllllllllk",
      "kllllllllllllllk",
      "kllllllllllllllk",
      "kllllllllllllllk",
      "kkkkkkkkkkkkkkkk"] },
    tree: { group:"props", sym:true, note:"Malezor fruit tree. Violet fruit (v) can be recoloured per district.",
      rows:["......kk",
      "....kkhh",
      "...khhgg",
      "..khggGg",
      ".khgGGgv",
      ".khvgggg",
      "khggGgvg",
      "khgGGggg",
      "khhgggvh",
      "khvhgggg",
      "khhhhggh",
      ".khhvhhh",
      ".khhhhhh",
      "..khhhhh",
      "...kkhhh",
      ".....kkb",
      "......kb",
      "......kb",
      "......kB",
      "......kb",
      ".....kbb",
      "....kbub",
      "....kkkk",
      "........"] },
    shrub: { group:"props", sym:true, note:"Metallic-leafed shrub with glassy blue seed-pods.",
      rows:["........",
      "........",
      "........",
      "........",
      "........",
      "....kkkk",
      "...khhgh",
      "..khgGgc",
      ".khgGgcC",
      ".khhggcc",
      "khgchhhg",
      "khgCchgg",
      "khhcchhh",
      ".khhhhhh",
      "..kkkkkk",
      "........"] },
    boulder: { group:"props", sym:true,
      rows:["........",
      "........",
      "........",
      "........",
      "....kkkk",
      "...kWWnn",
      "..kWWnnn",
      ".kWnnnnn",
      ".kWnnnnN",
      "knnnnnNN",
      "knnnNNNN",
      "knnNNNNN",
      ".kNNNNNN",
      "..kkkkkk",
      "........",
      "........"] },
    astralite: { group:"props", sym:true,
      rows:["........",
      "........",
      "........",
      ".......k",
      "......kC",
      "...k..kc",
      "..kCk.kc",
      "..kck.kc",
      "..kckkcc",
      "..kccccc",
      ".kNkcccc",
      ".kNNkccc",
      "kNnNNkkk",
      "kNNnNNNN",
      ".kkkkkkk",
      "........"] },
    astralite1: { group:"props", sym:true, pal:{"c": "#bff0ff", "C": "#ffffff"}, note:"Glow frame of the Astralite (same pixels, brighter palette).",
      rows:["........",
      "........",
      "........",
      ".......k",
      "......kC",
      "...k..kc",
      "..kCk.kc",
      "..kck.kc",
      "..kckkcc",
      "..kccccc",
      ".kNkcccc",
      ".kNNkccc",
      "kNnNNkkk",
      "kNNnNNNN",
      ".kkkkkkk",
      "........"] },
    markings: { group:"props",
      rows:["................",
      "................",
      "....kkkkkkkk....",
      "...kLLLLLLLLk...",
      "..kLLyLLLyyLLk..",
      "..kLyyyLLyLLLk..",
      "..kLLyLLLyyLLk..",
      "..kLLLLLLLLLLk..",
      "..kLyyLyLyyyLk..",
      "..kLLyLyLLyLLk..",
      "..kLLLLLLLLLLk..",
      "..klLLLLLLLLlk..",
      "..kllllllllllk..",
      "..kkkkkkkkkkkk..",
      "................",
      "................"] },
    sign: { group:"props",
      rows:["................",
      "................",
      "..kkkkkkkkkkkk..",
      "..kBBBBBBBBBBk..",
      "..kBkkkBkkBBBk..",
      "..kBBBBBBBBBBk..",
      "..kBkkBkkkkBBk..",
      "..kbbbbbbbbbbk..",
      "..kkkkkkkkkkkk..",
      "......kbbk......",
      "......kbbk......",
      "......kbbk......",
      "......kbuk......",
      ".....hkbbkh.....",
      "................",
      "................"] },
    ship: { group:"props", sym:true, note:"Carl Nasaro's experimental 1936 rocket. Riveted steel, red fins, brass band.",
      rows:["...........k",
      "..........kr",
      "..........kr",
      ".........krR",
      ".........krR",
      "........krrR",
      "........krrR",
      ".......kkkkk",
      ".......kMmmm",
      ".......kMmmm",
      ".......kMmkk",
      ".......kMkeE",
      ".......kMkeE",
      ".......kMmkk",
      ".......kMmmm",
      ".......kMmmm",
      ".......kMmyy",
      ".......kMmmm",
      ".......kMmmm",
      ".......kMmmm",
      ".......kMmmm",
      "......kkMmmm",
      ".....krkMmmm",
      "....krRkMmmm",
      "...krRRkMmmm",
      "..krRRRkMmmm",
      "..krRRRkMmmm",
      ".krRRRRkkkkk",
      ".kkkkkk.kNNN",
      "........kNNN",
      ".........kkk"] },
    carl_down: { group:"carl", sym:true, note:"Copper pressure helmet, khaki 1936 expedition suit, brass buckle.",
      rows:["......kk",
      "....kkoO",
      "...koOkk",
      "...kokeE",
      "..koOkeE",
      "..kookee",
      "...kookk",
      "....kkMM",
      "...ksSSs",
      "..ksSSsy",
      "..ksdsss",
      "..kOksss",
      "...ksssd",
      "...kssk.",
      "...kdNk.",
      "...kkkk."] },
    carl_down1: { group:"carl",
      rows:["......kkkk......",
      "....kkoOOokk....",
      "...koOkkkkOok...",
      "...kokeEEekok...",
      "..koOkeEEekOok..",
      "..kookeeeekook..",
      "...kookkkkook...",
      "....kkMMMMkk....",
      "...ksSSssSSsk...",
      "..ksSSsyysSSsk..",
      "..ksdssssssdsk..",
      "..kOksssssskOk..",
      "...ksssddsssk...",
      "...kssk..kssk...",
      "...kkkk..kdNk...",
      "..........kkkk.."] },
    carl_up: { group:"carl", sym:true, note:"Back view: brass air tank on the back.",
      rows:["......kk",
      "....kkoO",
      "...koOOo",
      "...koooo",
      "..koOooo",
      "..kooooo",
      "...kookk",
      "....kkMM",
      "...ksSky",
      "..ksSSky",
      "..ksdsky",
      "..kOkssk",
      "...ksssd",
      "...kssk.",
      "...kdNk.",
      "...kkkk."] },
    carl_up1: { group:"carl",
      rows:["......kkkk......",
      "....kkoOOokk....",
      "...koOOooOOok...",
      "...kooooooook...",
      "..koOooooooOok..",
      "..kooooooooook..",
      "...kookkkkook...",
      "....kkMMMMkk....",
      "...ksSkyykSsk...",
      "..ksSSkyykSSsk..",
      "..ksdskyyksdsk..",
      "..kOksskksskOk..",
      "...ksssddsssk...",
      "...kssk..kssk...",
      "...kkkk..kdNk...",
      "..........kkkk.."] },
    carl_side: { group:"carl", note:"Facing right; mirrored for left.",
      rows:["......kkkk......",
      ".....kooOOkk....",
      "....koOOkkkOk...",
      "....kooOkeEEk...",
      "...kooookeEEEk..",
      "...kooookeeek...",
      "....kkookkkk....",
      ".....kMMMk......",
      "....kysSSsk.....",
      "...kyysSSSsk....",
      "...kyysdssk.....",
      "....kksssOk.....",
      ".....ksssk......",
      ".....ksssk......",
      ".....kdkNk......",
      ".....kkkkk......"] },
    carl_side1: { group:"carl",
      rows:["......kkkk......",
      ".....kooOOkk....",
      "....koOOkkkOk...",
      "....kooOkeEEk...",
      "...kooookeEEEk..",
      "...kooookeeek...",
      "....kkookkkk....",
      ".....kMMMk......",
      "....kysSSsk.....",
      "...kyysSSSsk....",
      "...kyysdssk.....",
      "....kksssOk.....",
      ".....ksssk......",
      "....ksk.ksk.....",
      "...kdk...kNk....",
      "...kkk...kkk...."] },
    haemen_down: { group:"haemen", sym:true, note:"Fur-clad Malezor inhabitant: heavy cap, beard, fur collar.",
      rows:["......kk",
      "....kkuu",
      "...kuubb",
      "...kuuuu",
      "...kttkt",
      "...ktbbb",
      "..kWbbbb",
      ".kWWuuub",
      ".kWuuuyu",
      ".kWuuuuu",
      ".ktkuuuu",
      "..kuuuuu",
      "..kuuuWW",
      "...kuuk.",
      "...kNNk.",
      "...kkkk."] },
    haemen_up: { group:"haemen", sym:true,
      rows:["......kk",
      "....kkuu",
      "...kuubb",
      "...kuuuu",
      "...kuuuu",
      "...kbuuu",
      "..kWWWWW",
      ".kWWuuuu",
      ".kWuuuuu",
      ".kWuuuuu",
      ".ktkuuuu",
      "..kuuuuu",
      "..kuuuWW",
      "...kuuk.",
      "...kNNk.",
      "...kkkk."] },
    haemen_side: { group:"haemen",
      rows:["......kkkk......",
      "....kkuuuuk.....",
      "...kuubbbbuk....",
      "...kuuuuuuuk....",
      "....kuuttktk....",
      "....ktttbbbk....",
      "...kWWbbbbbk....",
      "..kWWuuuubWk....",
      "..kWuuuuyuWk....",
      "..kWuuuuuuk.....",
      "...kWuuuutk.....",
      "...kuuuuuk......",
      "...kuuuuWWk.....",
      "....kuuk........",
      "....kNNk........",
      "....kkkk........"] },
    otterlin_side: { group:"zyrex", note:"Otterlin · Tier I · Beast/Aquatic. Navy fur, pale belly.",
      rows:["................",
      "................",
      "................",
      "................",
      "...........kkk..",
      "..........kiIIk.",
      "..........kikIkk",
      ".........kiiiijk",
      "..kkkkkkkiiiijk.",
      ".kiiiiiiiiijjk..",
      "kiIiiiiiijjjk...",
      "kik.kiiiijjjk...",
      ".k..kiik.kiik...",
      "....kiik.kiik...",
      "....kkkk.kkkk...",
      "................"] },
    otterlin_side1: { group:"zyrex",
      rows:["................",
      "................",
      "................",
      "................",
      "...........kkk..",
      "..........kiIIk.",
      "..........kikIkk",
      ".........kiiiijk",
      "..kkkkkkkiiiijk.",
      ".kiiiiiiiiijjk..",
      "kiIiiiiiijjjk...",
      "kik.kiiiijjjk...",
      ".k..kik..kik....",
      "...kik....kik...",
      "...kkk....kkk...",
      "................"] },
    otterlin_down: { group:"zyrex", sym:true,
      rows:["........",
      "........",
      "........",
      "........",
      "....kk..",
      "...kiIkk",
      "...kiiii",
      "..kiwkii",
      "..kiiijj",
      "...kijjk",
      "..kiijjj",
      ".kiiijjj",
      ".kiiijjj",
      "..kiikjj",
      "..kiik..",
      "..kkkk.."] },
    verdanix_side: { group:"zyrex", note:"Verdanix · Tier I · Beast/Verdant. Cloaked in leaves, carries a stick.",
      rows:["................",
      ".........kkk....",
      "........kwkQk...",
      "........kQQQQk..",
      ".......kqQQQQQk.",
      ".......kqqkkkk..",
      "......kxxqqk..b.",
      ".....kxhhxxk.b..",
      "....kxhhhhxkb...",
      "....kxhhhhhxb...",
      "....kxhhhhhxb...",
      ".....kxhhhxk.b..",
      "......kqqqk..b..",
      "......kqkqk..b..",
      ".....kqk.kqk....",
      ".....kkk.kkk...."] },
    verdanix_side1: { group:"zyrex",
      rows:["................",
      ".........kkk....",
      "........kwkQk...",
      "........kQQQQk..",
      ".......kqQQQQQk.",
      ".......kqqkkkk..",
      "......kxxqqk..b.",
      ".....kxhhxxk.b..",
      "....kxhhhhxkb...",
      "....kxhhhhhxb...",
      "....kxhhhhhxb...",
      ".....kxhhhxk.b..",
      "......kqqqk..b..",
      ".....kqk..kqk.b.",
      "....kqk....kqk..",
      "....kkk....kkk.."] },
    verdanix_down: { group:"zyrex", sym:true,
      rows:["........",
      "..kkk...",
      ".kwkQk..",
      ".kQQQkkk",
      ".kqQQQQQ",
      "..kqqkkk",
      "..kxxqqq",
      ".kxhxxqq",
      ".kxhhxxq",
      ".kxhhhxx",
      ".kxhhhhx",
      "..kxhhhh",
      "..kxxhhh",
      "...kqqkk",
      "..kqqqk.",
      "..kkkkk."] },
    aetherwing: { group:"zyrex", sym:true, note:"Aetherwing · Tier I · Beast/Radiant. Luminous violet wings.",
      rows:["........",
      ".......k",
      "......kc",
      "......kC",
      ".kkk..kc",
      "kVVVkkkc",
      "kVVVVVkc",
      ".kVVVVkc",
      "..kkkkkc",
      "kVVVkkkc",
      ".kVVVVkc",
      "..kkkk.k",
      "......kc",
      "......kc",
      ".......k",
      "........"] },
    aetherwing1: { group:"zyrex", sym:true,
      rows:["........",
      ".......k",
      "......kc",
      "......kC",
      "......kc",
      "..kkkkkc",
      ".kVVVVkc",
      "..kkkkkc",
      "......kc",
      "..kkkkkc",
      ".kVVVVkc",
      "..kkkk.k",
      "......kc",
      "......kc",
      ".......k",
      "........"] },
    volcanut_down: { group:"zyrex", sym:true, note:"Volcanut · Tier I · Beast/Aura. Spined, glowing like a stove.",
      rows:["........",
      "..k..k..",
      "..kRkkRk",
      ".kRRRRRR",
      ".krrRRRR",
      "krrkyrrr",
      "krrrrrrr",
      "krrrrkkk",
      ".krrrrrr",
      "kRrrrrrr",
      "kRkrrrrr",
      "kRkrrrrr",
      ".kkrrkrr",
      "..krrk..",
      "..kuuk..",
      "..kkkk.."] },
    volcanut_side: { group:"zyrex",
      rows:["................",
      "........k.k.k...",
      ".......kRkRkRk..",
      "......kRRRRRRRk.",
      "....kkrrRRRRkyk.",
      "...krrrrrrrrrrrk",
      "..krRrrrrrrrrkkk",
      ".krRrrrrrrrrrrk.",
      ".kRrrrrrrrrrrk..",
      "kRkrrrrrrrrrrk..",
      "kRk.krrrkkrrrk..",
      ".k..krrk.krrk...",
      "....kuuk.kuuk...",
      "....kkkk.kkkk...",
      "................",
      "................"] },
    volcanut_side1: { group:"zyrex",
      rows:["................",
      "........k.k.k...",
      ".......kRkRkRk..",
      "......kRRRRRRRk.",
      "....kkrrRRRRkyk.",
      "...krrrrrrrrrrrk",
      "..krRrrrrrrrrkkk",
      ".krRrrrrrrrrrrk.",
      ".kRrrrrrrrrrrk..",
      "kRkrrrrrrrrrrk..",
      "kRk.krrrkkrrrk..",
      ".k..krk...krk...",
      "...kuk.....kuk..",
      "...kkk.....kkk..",
      "................",
      "................"] },
    grid: { group:"tiles", note:"Lattice plate. Lines glow (c); recolour per world.",
      rows:["cccccccccccccccc",
      "clllllllclllllll",
      "clllllllclllllll",
      "clllllllclllllll",
      "clllClllclllClll",
      "clllllllclllllll",
      "clllllllclllllll",
      "clllllllclllllll",
      "cccccccccccccccc",
      "clllllllclllllll",
      "clllllllclllllll",
      "clllllllclllllll",
      "clllClllclllClll",
      "clllllllclllllll",
      "clllllllclllllll",
      "clllllllclllllll"] },
    ripple: { group:"tiles", note:"Concentric sound-ripple stone.",
      rows:["nNNWWNNNNNNWWNNn",
      "NNWNNnnnnnnNNWNN",
      "NWNNnnNNNNnnNNWN",
      "WNNnNNWWWWNNnNNW",
      "WNnNWWNNNNWWNnNW",
      "NnnNWNnnnnNWNnnN",
      "NnNWNnnNNnnNWNnN",
      "NnNWNnNWWNnNWNnN",
      "NnNWNnNWWNnNWNnN",
      "NnNWNnnNNnnNWNnN",
      "NnnNWNnnnnNWNnnN",
      "WNnNWWNNNNWWNnNW",
      "WNNnNNWWWWNNnNNW",
      "NWNNnnNNNNnnNNWN",
      "NNWNNnnnnnnNNWNN",
      "nNNWWNNNNNNWWNNn"] },
    cracks: { group:"tiles", note:"Basalt plate split by glowing seams.",
      rows:["nNNNNRrnNNNNNNnN",
      "NNNNNRrNNNNNnNNN",
      "NNNnNRrNNNnNNNNN",
      "RRRRRRrNnNNNNNNn",
      "NNNNNRrNNNNNNnNN",
      "NNNNnRrNNNNnNNNN",
      "NNnNNRrNNnNNNNNN",
      "nNNNNRrnNNNNNNnN",
      "NNNNNRrNNNNNnNNN",
      "NNNnNRRRRRRRRNNN",
      "NnNNNrrrrrrrRNNn",
      "NNNNNNnNNNNNRnNN",
      "NNNNnNNNNNNnRNNN",
      "NNRNNNNNNnNNRNNN",
      "nNRNNNNnNNNNRNnN",
      "NNRNNnNNNNNNRNNN"] },
    rail: { group:"tiles", note:"Iron rail on sleepers.",
      rows:["PNNNMmNNNPNMmNNN",
      "NNbbMmbbbbbMmbNN",
      "NNNNMmNNNNNMmPNN",
      "NNNNMmPNNNNMmNNP",
      "NNNNMmNNPNNMmNNN",
      "NPbbMmbbbbbMmbNN",
      "NNNPMmNNNNNMmNNN",
      "NNNNMmNNNNNMmNPN",
      "NNNNMmNPNNNMmNNN",
      "PNbbMmbbbbbMmbNN",
      "NNPNMmNNNNNMmNNN",
      "NNNNMmNNNNNMmPNN",
      "NNNNMmPNNNNMmNNP",
      "NNbbMmbbbbbMmbNN",
      "NPNNMmNNNNPMmNNN",
      "NNNPMmNNNNNMmNNN"] },
    cloud: { group:"tiles", note:"Cloud sea below a floating island. Not walkable.",
      rows:["WAAAAWwAwAAWAAAA",
      "AAWAAAAWwAwAAWAA",
      "AwAAWAAAAWwAwAAW",
      "WwAwAAWAAAAWwAwA",
      "AAWwAwAAWAAAAWwA",
      "AAAAWwAwAAWAAAAW",
      "AWAAAAWwAwAAWAAA",
      "wAAWAAAAWwAwAAWA",
      "wAwAAWAAAAWwAwAA",
      "AWwAwAAWAAAAWwAw",
      "AAAWwAwAAWAAAAWw",
      "WAAAAWwAwAAWAAAA",
      "AAWAAAAWwAwAAWAA",
      "AwAAWAAAAWwAwAAW",
      "WwAwAAWAAAAWwAwA",
      "AAWwAwAAWAAAAWwA"] },
    spire: { group:"props", sym:true, note:"Crystal spire (recolour per world: crystal, ice, glass).",
      rows:["......kk",
      ".....kCC",
      ".....kCc",
      "....kCCc",
      "....kCcc",
      "....kCcc",
      "...kCCcc",
      "...kCccc",
      "...kCccc",
      "..kCCccc",
      "..kCcccc",
      "..kCcccc",
      ".kCCcccc",
      ".kCccccc",
      "kNnNNNNN",
      "kkkkkkkk"] },
    pillar: { group:"props", note:"Ruined pillar.",
      rows:["................",
      "....kkkkkkkk....",
      "....kWWnnnnk....",
      ".....kWnnnk.....",
      ".....kWnnnk.....",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      ".....kWnNNk.....",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      "....kkWnnNkk....",
      "...kWWWnnnNNk...",
      "...kkkkkkkkkk...",
      "................",
      "................"] },
    vent: { group:"props", note:"Fumarole venting steam or flame.",
      rows:["................",
      "................",
      "................",
      ".......WW.......",
      "......W..W......",
      ".......WW.......",
      "......W..W......",
      ".......Rr.......",
      "......kRRk......",
      ".....kNRRNk.....",
      "....kNNrrNNk....",
      "...kNnNNNNnNk...",
      "...kNNNNNNNNk...",
      "....kkkkkkkk....",
      "................",
      "................"] },
    pylon: { group:"props", sym:true, note:"Machine pylon with brass beacon.",
      rows:["......kk",
      ".....kyy",
      ".....kYy",
      "......kk",
      "......kM",
      ".....kMm",
      ".....kMm",
      "....kkMm",
      "...kmmMm",
      "...kmkMm",
      "...kmmMm",
      "....kkMm",
      ".....kMm",
      "....kMMm",
      "...kMMMM",
      "..kkkkkk"] },
    deadtree: { group:"props", note:"Leafless tree (ash, frost or bone, by palette).",
      rows:["................",
      "..k.......k.....",
      "..kk..k..kk.....",
      "...kk.kkkk...k..",
      "....kkbbk...kk..",
      "......kbk.kkk...",
      "......kbbkk.....",
      "......kbbk......",
      ".......kbk......",
      ".......kbk......",
      ".......kbk......",
      "......kbbk......",
      ".....kbubbk.....",
      ".....kkkkkk.....",
      "................",
      "................"] },
    astranav: { group:"props", note:"The AstraNav Mk. I: cream enamel case, green phosphor screen, brass dial.", pal:{"x":"#13301a","Q":"#7cf08a","W":"#d8cfb4","w":"#f4efe0","y":"#b08d57","Y":"#e2c27d","r":"#c8402c"},
      rows:["................",
      "...kkkkkkkkkk...",
      "..kwwwwwwwwwwk..",
      "..kwkkkkkkkkwk..",
      "..kwkxxxxxxkwk..",
      "..kwkxQxxxxkwk..",
      "..kwkxxQxQxkwk..",
      "..kwkxxxQxxkwk..",
      "..kwkkkkkkkkwk..",
      "..kwWWWWWWWWwk..",
      "..kwyYWWWWrWwk..",
      "..kwYyWyyWWWwk..",
      "..kwWWWWWWWWwk..",
      "...kwwwwwwwwk...",
      "....kkkkkkkk....",
      "................"] },
    // ── NASARUS HQ (generated) ──
    hq_tent: { group:"hq", note:"Camp shelter: canvas, a flag, a crate of supplies.",
      rows:["................................",
      "................kkkkk...........",
      "...............kbrrrrk..........",
      "...............kbwwwwk..........",
      "...............kbkkkk...........",
      "..............kSbk..............",
      "..............kSsk..............",
      ".............kSSssk.............",
      "............kSSSsssk............",
      "...........kSSSSssssk...........",
      "..........kSSSSSsssssk..........",
      ".........kSSSSSSssssssk.........",
      "........kSSSSSSSsssssssk........",
      ".......kSSSSSSSuusssssssk.......",
      "......kSSSSSSSSuussssssssk......",
      ".....kSSSSSSSSuuuussssssssk.....",
      "....kSSSSSSSSSuuuussssssssskkk..",
      "...kSSSSSSSSSuuuuuusssssBBBBBBk.",
      "..kSSSSSSSSSSuuuuuusssssuuuuuuk.",
      ".kSSSSSSSSSSuuuuuuuussssBBBBBBk.",
      "kbSSSSSSSSSSuuuuuuuussssBBBBBBbk",
      ".kddddddddddddddddddddddddddddk.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "................................"] },
    hq_crate: { group:"hq", note:"The initial stores: one stout crate.",
      rows:[".....kkkkkk.....",
      "....kPPPPPPk....",
      "....kbbbbbbk....",
      "..kkkbbbbbbkkk..",
      ".kmPPPPuPPPPPmk.",
      ".kBBBBBuBBBBBBk.",
      ".kBBBBBuBBBBBBk.",
      ".kBBBBBuBBBBBBk.",
      ".kuuuuuuuuuuuuk.",
      ".kBBBBBuBBBBBBk.",
      ".kBBBBBuBBBBBBk.",
      ".kBBBBBuBBBBBBk.",
      ".kBBBBBuBBBBBBk.",
      ".kmBBBBuBBBBBmk.",
      "..kkkkkkkkkkkk..",
      "................"] },
    hq_lab: { group:"hq", note:"Research Station: field table, microscope, papers, lamp.",
      rows:["................................",
      "........................kkkk....",
      ".......................kyyyyk...",
      ".....kkkkk.............kyyyyk...",
      "....kmmmmmk.............kYkk....",
      "....kmmmmmk..............k......",
      ".....kMMMk...............k......",
      ".....kMMMk.....kkkkkkkk..k......",
      ".....kMMMkkkk.kwwwwwwwwk.k......",
      ".....kMMMkmmmkkwWWWWWWwk.k......",
      ".....kMMMkmmmkkwWWWWWwwk.k......",
      "..kkkkMMMkmmmkkwwwwwwwwkkkkkkk..",
      ".kPPPPPPPPPPPPPPPPPPPPPPPPPPPPk.",
      ".kBBBBBBBBBBBBBBBBBBBBBBBBBBBBk.",
      ".kBBBBBBBBBBBBBBBBBBBBBBBBBBBBk.",
      "..kuukkkkkkkkkkkkkkkkkkkkkkuuk..",
      "..kuuk....................kuuk..",
      "..kuuk....................kuuk..",
      "..kuuk....................kuuk..",
      "..kuuk....................kuuk..",
      "..kuuk....................kuuk..",
      "..kuuk....................kuuk..",
      "...kk......................kk...",
      "................................"] },
    hq_nav: { group:"hq", note:"Navigation Center: riveted hut and lattice mast with a dish.",
      rows:["................k...............",
      "...............krk..............",
      "...........kkkkkRkkkk...........",
      "..........kwwwwwwwwwwk..........",
      ".........kmmmmmmmmmmmmk.........",
      ".........kmmmmmmmmmmmmk.........",
      "..........kkkkkMMMkkkk..........",
      "..............kMkMk.............",
      "..............kMkMk.............",
      "..............kMMMk.............",
      "..............kMkMk.............",
      ".............kMkkkMk............",
      ".............kMMMMMk............",
      ".............kMkkkMk............",
      ".............kMkkkMk............",
      ".............kMMMMMk............",
      ".............kMkkkMk............",
      ".............kMkkkMk............",
      "............kMMMMMMMk...........",
      "............kMkkkkkMk...........",
      "............kMkkkkkMk...........",
      "............kMMMMMMMk...........",
      "............kMkkkkkMk...........",
      "............kMkkkkkMk...........",
      "............kMMMMMMMk...........",
      "...kkkkkkkkkMkkkkkkkMkkkkkkkk...",
      "..kWWWWWWWWWWWWWWWWWWWWWWWWWWk..",
      "..kmmmmmmmmmmmmmmmmmmmmmmmmmmk..",
      "..kmmMmmmMmmmMmmmMmmmxxxxxmmmk..",
      "..kmmmmmmmmmmmmmmmmmmxQxxxmmmk..",
      "..kmmmmmmmmmmiiiiiimmxxxQxmmmk..",
      "..kmmmmmmmmmmiiiiiimmxxxxxmmmk..",
      "..kmmmmmmmmmmiiiiiimmmmmmmmmmk..",
      "..kmmmmmmmmmmiiiiiimmmmmmmmmmk..",
      "..kmmmmmmmmmmiiiiiimmmmmmmmmmk..",
      "..kmmMmmmMmmmMiiiMimmMmmmMmmmk..",
      "..kmmmmmmmmmmiiiiiimmmmmmmmmmk..",
      "..kmmmmmmmmmmiiiiiimmmmmmmmmmk..",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "................................"] },
    hq_depot: { group:"hq", note:"Resource Depot: corrugated shed and crates.",
      rows:["................................",
      "................................",
      "................................",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      ".kmmmmmmmmmmmmmmmmmmmmmmmmmmmmk.",
      "kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk",
      ".kMmMMmMMmMMmMMmMMmMMmMMmMMmMMk.",
      ".kMmMMmMMmMMmMMmMMmMMmMMmMMmMMk.",
      ".kMmMMmMMmMMmMMmMMmMMmMMmMMmMMk.",
      ".kMmMMmMMmMMmMMmMMmMMmMMmMMmMMk.",
      ".kMmMMmMMmMMmMMmMMmMMmMMmMMmMMk.",
      ".kMmMMmMMmnnnnnnnnnnnnMMmMMmMMk.",
      ".kMmMMmMMmnnnnnnnnnnnnMMmMMmMMk.",
      ".kMmMMmMMmnnnnnnnnnnnnMMmMMmMMk.",
      ".kMmMMmMMmNNNNNNNNNNNNMMmMMmMMk.",
      ".kMmMMmMMmnnnnnnnnnnnnMMmMMmMMk.",
      ".kMmMMmMMmnnnnnnnnnnnnMMBBBBBBk.",
      ".kMmMMmMMmNNNNNNNNNNNNMMBBBBBBk.",
      ".kMmMMmMMmnnnnnnnnnnnnMMuuuuuuk.",
      ".kMmMMmMMmnnnnnnnnnnnnMMBBBBBBk.",
      ".kMmMMmMMmnnnnnnnnnnnnMMBBBBBBk.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "................................",
      "................................"] },
    hq_workshop: { group:"hq", note:"Workshop: riveted copper hut, brick chimney.",
      rows:["..........................knk...",
      "..........................kkWk..",
      ".........................kRRRRk.",
      ".........................krrrrk.",
      ".........................krrrrk.",
      ".........................krrrrk.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkrrrrk.",
      ".koooooooooooooooooooooooorrrrk.",
      "..kooooooooooooooooooooookrrrrk.",
      "..kOOOOOOOOOOOOOOOOOOOOOOkrrrrk.",
      "..kOOuOOOuOOOuOOOuOOOuOOOkrrrrk.",
      "..kOOOOOOOOOOOOOOOOOOOOOOkrrrrk.",
      "..kOOOOOOOOOOOOOOOOOOOOOOkrrrrk.",
      "..kOOuOOOuuuuuuuuuOOOuOOOkrrrrk.",
      "..kOOOOOOOuuuuuuuOOOOOOOOkrrrrk.",
      "..kOOOOOOOuuuuuuuOOOOOOOOkrrrrk.",
      "..kOOuOOOuuuuuuuuuOOOuOOOkrrrrk.",
      "..kOOOOOOOuuuuuuuOOOOOOOOkrrrrk.",
      "..kOOOOOOOuuuuuuuOOOOOOOOkrrrrk.",
      "..kOOuOOOuuuuuuuuuOOOuOOOkrrrrk.",
      "..kOOOOOOOuuuuuuuOOOOOOOOkrrrrk.",
      "...kkkkkkkkkkkkkkkkkkkkkk.kkkk..",
      "................................",
      "................................"] },
    hq_archive: { group:"hq", note:"Card Archive: a timber cabinet-house.",
      rows:["................................",
      "................................",
      "................................",
      "................................",
      "......kkkkkkkkkkkkkkkkkkkk......",
      "....kkbbbbbbbbbbbbbbbbbbbbkk....",
      "..kkPPPPPPPPPPPPPPPPPPPPPPPPkk..",
      ".kPPPPPPPPPPPPPPPPPPPPPPPPPPPPk.",
      "..kppppppppppppppppppppppppppk..",
      "..kppppppppppppppppppppppppppk..",
      "..kppppppppppppppppppppppppppk..",
      "..kpppwwwwwppppppppppwwwwwpppk..",
      "..kpppwyyywppppppppppwyyywpppk..",
      "..kpppwyyywppuuuuuuppwyyywpppk..",
      "..kpppwyyywppuuuuuuppwyyywpppk..",
      "..kpppwwwwwppuuuuuuppwwwwwpppk..",
      "..kppppppppppuuuuuuppppppppppk..",
      "..kppppppppppuuuuuuppppppppppk..",
      "..kppppppppppuuuuuuppppppppppk..",
      "..kppppppppppuuuuuuppppppppppk..",
      "..kppppppppppuuuuuuppppppppppk..",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "................................",
      "................................"] },
    hq_terminal: { group:"hq", note:"Restoration Terminal: console with a green screen.",
      rows:["................",
      "................",
      "................",
      "................",
      "................",
      "...kkkkkkkkkk...",
      "..kWWWWWWWWWWk..",
      "..kMMMMMMMMMMk..",
      "..kMxxxxxxxxMk..",
      "..kMxxQxxxxxMk..",
      "..kMxQQQQQQxMk..",
      "..kMxxxxxxxxMk..",
      "..kMxxxxxxxxMk..",
      "..kMxxxxxxxxMk..",
      "..kMMMMMMMMMMk..",
      "..kMMMMMMMMMMk..",
      "..kMMyMMyMMrMk..",
      "..kMMMMMMMMMMk..",
      "..kMmmmmmmmmMk..",
      "..kMMMMMMMMMMk..",
      "..kMMMMMMMMMMk..",
      "...kkkkkkkkkk...",
      "................",
      "................"] },
    hq_history: { group:"hq", note:"Historical Archive: canvas pavilion over a stone plinth.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "................................",
      "................................",
      "..............kkkk..............",
      "............kkSSsskk............",
      "..........kkSSSSsssskk..........",
      "........kkSSSSSSsssssskk........",
      "......kkSSSSSSSSsssssssskk......",
      "....kkSSSSSSSSSSsssssssssskk....",
      "..kkSSSSSSSSSSSSsssssssssssskk..",
      "kkSSSSSSSSSSSSSSsssssssssssssskk",
      "SSSSSbSSSSSSSvvVvvvsssssssbsssss",
      "kkkkkbkkkkkkkvvvvvvkkkkkkkbkkkkk",
      "....kbk.....kvvvvvvk.....kbk....",
      "....kbkkkkkkkvvvvvvkkkkkkkbk....",
      "...kWWWWWWWWWWWWWWWWWWWWWWWWk...",
      "...kWnnnnnnnnnnnnnnnnnnnnnNNk...",
      "...kWnnnnnnnnnnnnnnnnnnnnnNNk...",
      "...kWnnnnnnnnnnnnnnnnnnnnnNNk...",
      "...kWnnnnnnnnnnnnnnnnnnnnnNNk...",
      "...kWnnnnnnnnnnnnnnnnnnnnnNNk...",
      "....kkkkkkkkkkkkkkkkkkkkkkkk....",
      "................................",
      "................................"] },
    hq_plot: { group:"hq", note:"A staked plot, waiting to be built.",
      rows:["..k..........k..",
      ".kbk.k.k.k.kkbk.",
      ".kbpkpkpkpkpkbk.",
      ".kbk.k.k.k.kkbk.",
      ".kbk........kbk.",
      "..k...kkkk...k..",
      ".....kPPPPk.....",
      ".....kPPPPk.....",
      ".....kPPPPk.....",
      "..k...kbkk...k..",
      ".kbk.kkbkk.kkbk.",
      ".kbpkpkbkpkpkbk.",
      ".kbk.kkbkk.kkbk.",
      ".kbk...k....kbk.",
      "..k..........k..",
      "................"] },
    hq_lamp: { group:"hq", note:"A camp lamp post.",
      rows:["................",
      ".....kkkkkk.....",
      "....kYYYYYYk....",
      "....kYFFFFYk....",
      "....kYFFFFYk....",
      "....kYFFFFYk....",
      "....kYYYYYYk....",
      ".....kkknkk.....",
      ".......knk......",
      ".......knk......",
      ".......knk......",
      ".......knk......",
      ".......knk......",
      ".......knk......",
      ".......knk......",
      ".......knk......",
      ".......knk......",
      ".......knk......",
      ".......knk......",
      ".......knk......",
      ".....kkknkk.....",
      "....kNNNNNNk....",
      ".....kkkkkk.....",
      "................"] },
    hq_scrap: { group:"hq", note:"Wreckage from the crash.",
      rows:["................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......kkkk.....",
      "......kMMMMk....",
      "...kkkkMMkMk....",
      "..kmmmmMMMMkkk..",
      "..kmmmmmmkooook.",
      "..kmmmmmmkooook.",
      ".kMMMMMkk.kkkk..",
      "..kkkkk.........",
      "................",
      "................"] },
    hq_rubble: { group:"hq", note:"Rockfall.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................",
      "................",
      "................",
      "..kkkk......kkk.",
      ".kNNNnkk...kNNNk",
      ".kNkkknnk..kNNk.",
      "..k..knnnkkWkk..",
      ".....knnnNNNk.kk",
      "...k..kNNNNNkkWW",
      ".kkNkkkNNNkWWWWW",
      "knnNWNnkkWWWWWkk",
      "knnnWNk.kWWWWWWN",
      ".knnnkkkkkkkWWWk",
      "kNNNNNNnnnNNNNWW",
      ".kNNkNNNNNNNNnWW",
      "..kkkNNkkkkNNkkk"] },
    rest_house: { group:"hq", note:"NASARUS \u00b7 restored. Ancient style not yet approved canon: neutral worked stone.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "................................",
      "................................",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      ".kNNNNNNNNNNNNNNNNNNNNNNNNNNNNk.",
      ".kWWWWWWWWWWWWWWWWWWWWWWWWWWWWk.",
      "..kWnnnnnnnnnnnnnnnnnnnnnnnNNk..",
      "..kWnnnnnnnnnnnnnnnnnnnnnnnNNk..",
      "..kWnnnnnnnnnnnnnnnnnnnnnnnNNk..",
      "..knnkkkkWnnnnnnnnnnnNNkkkknnk..",
      "..knnkkkkWnnnnnnnnnnnNNkkkknnk..",
      "..knnkkkkWnnnnnnnnnnnNNkkkknnk..",
      "..knnkkkkWnnNuuuuuuWnnNkkkknnk..",
      "..kWnnnnnnnNNuuuuuuWnnnnnnnNNk..",
      "..kWnnnnnnnNNuuuuuuWnnnnnnnNNk..",
      "..kWnnnnnnnNNuuuuuuWnnnnnnnNNk..",
      "..kWnnnnnnnNNuuuuuuWnnnnnnnNNk..",
      "..kWnnnnnnnNNuuuuuuWnnnnnnnNNk..",
      "..kPPPPPPPPPPPPPPPPPPPPPPPPPPk..",
      "..kWnnnnnnnNNuuuuuuWnnnnnnnNNk..",
      "..kWnnnnnnnNNuuuuuuWnnnnnnnNNk..",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "................................",
      "................................"] },
    ruin_house: { group:"hq", note:"NASARUS \u00b7 ruined state.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "........k.......................",
      ".......knk......................",
      "........k..k....................",
      "..........knk..k...........k....",
      "...k......knk.knk.........knk...",
      "..knkkkkk.knNkkukkk.kkkkk.knk...",
      "..kWknnnnkkNNuuukuuknnnnnknNNk..",
      "..kWknNnnnkNNuuukuuknnnnnknNNk..",
      "..kWknnNnnnNNuuukuuWnNnnnnnkNk..",
      "..kWnnnnnnnNNuuuuuuWnnnnnnnNNk..",
      "..kWnnnnnnnNNuuuuuuWnnnnnnnNNk..",
      "..kPPPPPPPPPPkPPPPPPPPPPPPPPPk..",
      "..kWnnnNnnnNNuuuuuuWnknnnnnNNk..",
      ".kkknnnnnnnNNuuuuuuWnnnnnnnNNk..",
      "kNNNkkkkkkkkWkkkkkkNkkkkkkkkWnk.",
      "knWknNk..kNkk...kWkk...knk.kWk..",
      ".kk.kk....k......k......k...k..."] },
    rest_hall: { group:"hq", note:"NASARUS \u00b7 restored. Ancient style not yet approved canon: neutral worked stone.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................................",
      "................................................",
      ".....................kkkkkk.....................",
      ".................kkkknnnnnnkkkk.................",
      ".............kkkknnnnyyyyyynnnnkkkk.............",
      ".........kkkknnnnnnnnyyyyyynnnnnnnnkkkk.........",
      ".....kkkknnnnnnnnnnnnyyyyyynnnnnnnnnnnnkkkk.....",
      ".kkkknnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnkkkk.",
      "kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk",
      ".kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNk.",
      "..kknnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnkk..",
      "...knnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnk...",
      "....kWWNkkkWWNkkkWWNkkkWWNkkkWWNkkkWWNkkkWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "..kkkWWNkkkWWNkkkWWNkkkWWNkkkWWNkkkWWNkkkWWNkk..",
      ".knnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnk.",
      ".kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNk.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "................................................"] },
    ruin_hall: { group:"hq", note:"NASARUS \u00b7 ruined state.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................................",
      "................................................",
      "................................................",
      "................................................",
      ".............k.k.k..............................",
      ".........kkkknknknk..................k..........",
      "........knnnnnknknk................kknk.........",
      "........knnnnnknnnk...............knnnnk........",
      "...k.k..kWWWWWWWWWWk.............kWWWWWk........",
      "..kNkNkkNNNNNNNNNNNk.............kNNNNNNk.......",
      "...knnknnnnnnnnnnnnk.k..........kknnnnnnk.......",
      "...knnnnnnnnnnnnnnnnknkk.......knnnnnnnnkkk.....",
      "....kWWNkkkWWNkkkWWNkkkWk.....k.kkkWWNkkkWWk....",
      "....kWWNk.kWWNk.kWWNk.kWk....kWk..kWWNk.kNWk....",
      "....kWWNk.kWWNk.kWWNk.kWk....kWNk.kWWNk.kNWk....",
      "....kWWNk.kWWNk.kWWNk.kWWk...kWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWk..kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWNNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "....kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk.kWWNk...",
      "..kkkWWNkkkWWNkkkWWNkkkWWNkkkWWNkkkWWNkkkkWNkk..",
      ".knnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnk.",
      ".kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNk.",
      "..kWkkkkkWnkkkkkkkWkkkkkknkknkkWkkkkkkkknkkkkk..",
      "...k.....kk.......k......k..k..k........k......."] },
    rest_obelisk: { group:"hq", note:"NASARUS \u00b7 restored. Ancient style not yet approved canon: neutral worked stone.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................",
      ".......kk.......",
      "......knnk......",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      ".....kWnnNk.....",
      "....kWnnnnNk....",
      "....kWnnnnNk....",
      "....kyyyyyyk....",
      "....kWnnnnNk....",
      "....kyyyyyyk....",
      "....kWnnnnNk....",
      "....kWnnnnNk....",
      "....kWnnnnNk....",
      "....kWnnnnNk....",
      "...kWnnnnnNNk...",
      "...kWnnnnnNNk...",
      "...kWnnnnnNNk...",
      "...kWnnnnnNNk...",
      "...kWnnnnnNNk...",
      "...kWnnnnnNNk...",
      "...kWnnnnnNNk...",
      "...kWnnnnnNNk...",
      "...kWnnnnnNNk...",
      "..kWnnnnnnnNNk..",
      "..kWnnnnnnnNNk..",
      "..kWnnnnnnnNNk..",
      "..kWnnnnnnnNNk..",
      "..kWnnnnnnnNNk..",
      "..kWnnnnnnnNNk..",
      "..kNNNNNNNNNNk..",
      "..kNNNNNNNNNNk..",
      "..kNNNNNNNNNNk..",
      "...kkkkkkkkkk..."] },
    ruin_obelisk: { group:"hq", note:"NASARUS \u00b7 ruined state.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "........kk......",
      ".......knNk.....",
      ".......knNk.....",
      ".......knNk.....",
      "......knnnNk....",
      "......knnnNk....",
      "......kyyyyk....",
      ".....knnnnNk....",
      "....kyyyyyyk....",
      "....kWnnnnNk....",
      "....kWnnnnNk....",
      "....kWnnnnNk....",
      "....kWNnnnNk....",
      "...kWnnnknNNk...",
      "...kWnnnnnNNk...",
      "...kWnnkNNNNk...",
      "...kWnnnnnNNk...",
      "...kWnnnnnNNk...",
      "...kWnNnnnNNk...",
      "...kWnnnnnNNk...",
      "...kWnknnnNNk...",
      "...kWnnnNnNNk...",
      "..kWnnnnnnnNNk..",
      "..kWknnnnnnNNk..",
      "..kWnnnnnnnNNk..",
      "..kWnnnnnnnNNk..",
      "..kWnnnnnnnNNk..",
      "..kWnnnnnnnNNk..",
      "..kNNNNNNNNNNkk.",
      ".kWNNNNNNNNNNnNk",
      ".kWNNNNNNNNNNnk.",
      "..kkkkkkkkkkkk.."] },
    rest_plaza: { group:"hq", note:"NASARUS \u00b7 restored. Ancient style not yet approved canon: neutral worked stone.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "...............kkk..............",
      "..............knnnk.............",
      "....kkk...kkk.knnnk.kkk...kkk...",
      "...knnnk.knnnkknnnkknnnk.knnnk..",
      "...knnnk.knnnkknnnkknnnk.knnnk..",
      "...knnnk.knnnkknnnkknnnk.knnnk..",
      "...knnnk.knnnkknnnkknnnk.knnnk..",
      "...knnnk.knnnkknnnkknnnk.knnnk..",
      "...knnnk.knnnkknnnkknnnk.knnnk..",
      "...knnnk.knnnkknnnkknnnk.knnnk..",
      "...knnnk.knnnkknnnkknnnk.knnnk..",
      "...knnnkkknnnkknnnkknnnkkknnnk..",
      "...knnnkPPnnnPPnnnPPnnnPPknnnk..",
      "...knnnPPPnnnPPnnnPPnnnPPPnnnk..",
      "...knnnPPPnnnPPnnnPPnnnPPPnnnk..",
      "..kPPPPPPPPPPPPPPPPPPPPPPPPPPPk.",
      "..kPPPPPPPPPPPPPPPPPPPPPPPPPPPk.",
      "..kPPPPPPPPPPPPPPPPPPPPPPPPPPPk.",
      "..kPPPPPPPPPPPPPPPPPPPPPPPPPPPk.",
      "...kPPPPPPPPPPPPPPPPPPPPPPPPPk..",
      "....kkPPPPPPPPPPPPPPPPPPPPPkk...",
      "......kkPPPPPPPPPPPPPPPPPkk.....",
      "........kkkkkkkkkkkkkkkkk......."] },
    ruin_plaza: { group:"hq", note:"NASARUS \u00b7 ruined state.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "................................",
      "................................",
      ".....k..........kk........k.k...",
      "....knk........knnk......knknk..",
      "....knk.....k..knnk......knnnk..",
      "....knk....knk.knnk...k..knnnk..",
      "...knnnk..knnk.knnk.kknk.knnnk..",
      "...knnnk.knnnk.knNkknknk.knnnk..",
      "....knnk.knnnkknnnkknknk.knnnk..",
      "...knnnk.knnnkknnnkknnnk.knnnk..",
      "...knnnk.knnnkknnNkknnnk.knnnk..",
      "...knnnkkknnnkknnnkknnnk.knnnk..",
      "...knknkPNnnnPPnnnPPnnnPkknnnk..",
      "...knnnPPPnnnPPnnnPPnnnPkPnnnk..",
      "...knnnPPPnnnPPnnnPPnnnkPPnnnk..",
      "..kPPPPPPPPPPPPPPPPPPPPPPPPPPPk.",
      "..kPPPPPPPPPPPPPPPPPPPPPPPPPPPk.",
      "..kPkNPPPkPkPPPPPkPPPPPPPPPPPPk.",
      "..kPPPPPPPPPkPPkPPPPPPPPPPPkPPk.",
      "..kkPPPPPPPPPPPPPPPPNPNPNPkPPkk.",
      ".kWkkkPPPPPPPPPPPPPPPPPPPPPNkkNk",
      "..knkkNkPPPPPPPPPPPPPPPPPkkk..k.",
      "...k..k.kkkkkkkkkkkkkkkkk......."] },
    rest_wall: { group:"hq", note:"NASARUS \u00b7 restored. Ancient style not yet approved canon: neutral worked stone.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "................................",
      ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
      "kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk",
      "kWnnnnnnnnnnnnnnnnnnnnnnnnnnnNNk",
      "kWnnnnnnnnnnnnnnnnnnnnnnnnnnnNNk",
      "kWnnnnnnnnnnnnnnnnnnnnnnnnnnnNNk",
      "kWnnnNynnnynnnynnnynnnyWnnnnnNNk",
      "kWnnnNynnnynnnynnnynnnyWnnnnnNNk",
      "kWnnnNynnnynnnynnnynnnyWnnnnnNNk",
      "kWnnNyyynyyynyyynyyynyyyWnnnnNNk",
      "kWnnnNynnnynnnynnnynnnyWnnnnnNNk",
      "kWnnnNynnnynnnynnnynnnyWnnnnnNNk",
      "kWnnnNynnnynnnynnnynnnyWnnnnnNNk",
      "kWnnnnnnnnnnnnnnnnnnnnnnnnnnnNNk",
      "kWnnnnnnnnnnnnnnnnnnnnnnnnnnnNNk",
      "kWnnnnnnnnnnnnnnnnnnnnnnnnnnnNNk",
      "kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNk",
      ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
      "................................"] },
    ruin_wall: { group:"hq", note:"NASARUS \u00b7 ruined state.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "................................",
      "..k.k.k.k.....k..k..............",
      ".kWkWkWkWk...kWkkWk.............",
      "kWnknknknnk..knkknnk............",
      "kWnknnnnnnk.knnkknnk............",
      "kWnnNnnnnnkknnnkNnnnk...........",
      "kWnnnNynnnynnnynnnynnk..........",
      "kWnknNynnnynnnynnnynNk..........",
      "kWnkkNynnnynnnynnnynnnk.kk......",
      "kWnnNyyynyyynyNynyyynykkWnkk.k..",
      "kWnnnNynnnynnnynnnynnnyWNnnnkNk.",
      "kWnnnNknnnknnnynnnynnnyWnnnnnNk.",
      "kWnnnNynnnynnnynnnynnnyWnnnnnNNk",
      "kWnnnnnNnnnnnnnnnnnnnnnnnnnnnNNk",
      "kNnnnnnnnnnNnnnNnnnnnnnnnnnnnNNk",
      "kWnnnknnnnnnnnnnnnnnnnnnnnnnnkNk",
      "kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNk",
      "kNkkNknkkkkknkkkkNkkkkkWknkkkkWk",
      ".k..k.k.....k....k.....k.k....k."] },
    rest_spire_old: { group:"hq", note:"NASARUS \u00b7 restored. Ancient style not yet approved canon: neutral worked stone.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "..............kkkk..............",
      ".............kCCCCk.............",
      ".............kCCCCk.............",
      ".............kCCCCk.............",
      ".............kCCCCk.............",
      ".............kWnnNk.............",
      ".............kWnnNk.............",
      ".............kWnnNk.............",
      ".............kWnnNk.............",
      ".............kWnnNk.............",
      ".............kWnnNk.............",
      "............kWnnnnNk............",
      "............kWnnnnNk............",
      "......kkkkkkkWnnnnNkkkkkkkk.....",
      "....kkcccccccWnnnnNcccccccckk...",
      "...kcccccccccWnnnnNcccccccccck..",
      "....kkcccccccWnnnnNcccccccckk...",
      "......kkkkkkWnnnnnNNkkkkkkk.....",
      "...........kWnnnnnNNk...........",
      "...........kWnnnnnNNk...........",
      "...........kWnnnnnNNk...........",
      "...........kWnnnnnNNk...........",
      "...........kWnnnnnNNk...........",
      "..........kWnnnnnnnNNk..........",
      "..........kWnnnnnnnNNk..........",
      "..........kWnnnnnnnNNk..........",
      "..........kWnnnnnnnNNk..........",
      "..........kWnnnnnnnNNk..........",
      "..........kWnnnnnnnNNk..........",
      ".........kWnnnnnnnnnNNk.........",
      ".........kWnnnnnnnnnNNk.........",
      ".........kWnnnnnnnnnNNk.........",
      ".........kWnnnnnnnnnNNk.........",
      ".........kWnnnnnnnnnNNk.........",
      "........kkWnnnnnnnnnNNkk........",
      ".......kNNNNNNNNNNNNNNNNk.......",
      ".......kNNNNNNNNNNNNNNNNk.......",
      ".......kNNNNNNNNNNNNNNNNk.......",
      "........kkkkkkkkkkkkkkkk........"] },
    ruin_spire_old: { group:"hq", note:"NASARUS \u00b7 ruined state.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "......................kkkk......",
      ".............k.......kNNNNkk....",
      "............kWk.....kkNNNNNNk...",
      "............kWnk...kNNNNNNNk....",
      "...........kWnnk.k..kkkkkkk.....",
      "...........kWnnkknk.............",
      "...........kWnnnnnkk............",
      "...........kWnnnnnkNk...........",
      "...........kWnnknnNNk...........",
      "...........kWnnnnkNNk...........",
      "..........kWnnnnnnnNNk..........",
      "..........kWnnnnnnnNNk..........",
      "..........kWnnnnknnNNk..........",
      "..........kWnnnnnnnNNk..........",
      "..........kWnnnnnnnNNk..........",
      "..........kWnnnNnnnNNk..........",
      ".........kWnnnnnnnnnNNk.........",
      ".........kWnnnnnnnnnNNk.........",
      ".........kWnnNnnnnnnNNk.........",
      ".........kWnnnnnnnnnNNk.........",
      ".........kWnnNnnnnnnNNk.........",
      "........kkWnnnnnnnnnNNkk........",
      "...k...kNNNNNNNNNNNNNNNNk.......",
      "..kNk.kkNNNNNNNNNNNNNNNNnk......",
      "..kWkknWNNNNNNNNNNNNNNNNk.......",
      "...k..kkkkkkkkkkkkkkkkkk........"] },
    ruin_vault: { group:"hq", note:"NASARUS \u00b7 a buried structure under a mound.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "............kkkkkkkk............",
      ".........kkkPPpPPPPpkkk.........",
      "......kkkPPPPpPPPPpPPPPkkk......",
      "...kkkPpPPPPpPnnnpPPPPpPPPkkk...",
      "..kPPPpPPnnnPPnnnPPPPpPPPPpPPk..",
      ".kPPPpPPPnnnPPPpPPPPnnnPPpPPPPk.",
      ".kPPpPPPPpPPPPpPPPPpnnnPpPPPPpk.",
      ".kPpPPPPpPPPPpPPPPpPPPPpPPPPpPk.",
      ".kpPPPPpPPPPpPPPPpPPPPpPPPPpPPk.",
      ".kPPPPpPPPPpPPPPpPPPPpPPPPpPPPk.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk.."] },
    rest_vault: { group:"hq", note:"NASARUS \u00b7 the buried structure, excavated.", pal:{"n": "#9a948a", "N": "#5e5a52", "W": "#cfc8b8", "P": "#a89670", "p": "#8a7a58", "y": "#c8a860", "c": "#7fb8c8", "C": "#c8f0ff"},
      rows:["................................",
      "................................",
      "................................",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "..kWWWWWWWWWWWWWWWWWWWWWWWWWWk..",
      "..kWnnnnnnnnnnnnnnnnnnnnnnnNNk..",
      "..kWnnnnnNNkkkkkkkkkkWnnnnnNNk..",
      "..kWnnnnnNNkNNNNNNNNkWnnnnnNNk..",
      "..kWnnnnnNNkkkkkkkkkkWnnnnnNNk..",
      "..kWnnnnnNNkkNNNNNNkkWnnnnnNNk..",
      "..kWnnnnnNNkkkkkkkkkkWnnnnnNNk..",
      "..kWnnnnnNNkkkNNNNkkkWnnnnnNNk..",
      "..kWnnnnnNNkkkkkkkkkkWnnnnnNNk..",
      "..kWnnnnnNNkkkkNNkkkkWnnnnnNNk..",
      "...kkkkkkkk....kk....kkkkkkkk...",
      "................................"] },
    // ── end NASARUS HQ ──
    face_m: { group:"portraits", sym:true, note:"Portrait base (man). Skin t/T, suit s/S/d, shirt W, tie y. Recoloured by the character creator.", pal:{"Z": "#5a3a22", "X": "#8a5c34", "t": "#e8c8a8", "T": "#c49a78"},
      rows:["............",
      "............",
      "........kkkk",
      "......kkTttt",
      ".....kTttttt",
      "....kTtttttt",
      "....kTtttttt",
      "....kTtttttt",
      "....kTtNNNtt",
      "....kTtwkktt",
      "....kTtttttt",
      "....kTtttttt",
      "....kTtttttT",
      "....kTttttTT",
      "....kTtttttt",
      ".....kTttTTT",
      ".....kTttttt",
      "......kTtttt",
      ".......kTTtt",
      "........kkTT",
      ".........kTt",
      "....kkkkkWWt",
      "..kkssSkWWWy",
      ".ksssSSSkWWy",
      ".kssSSSSkWyy",
      "ksssSSSSSkyy",
      "ksssSSSSSkWy",
      "ksdsSSSSSskW",
      "ksdssSSSSskW",
      "ksdssSSSSSkW",
      "ksdsssSSSSkW",
      "kkkkkkkkkkkk"] },
    face_f: { group:"portraits", sym:true, note:"Portrait base (woman). Skin t/T, suit s/S/d, blouse W, brooch y. Recoloured by the character creator.", pal:{"Z": "#5a3a22", "X": "#8a5c34", "t": "#e8c8a8", "T": "#c49a78"},
      rows:["............",
      "............",
      "........kkkk",
      "......kkTttt",
      ".....kTttttt",
      "....kTtttttt",
      "....kTtttttt",
      "....kTtttttt",
      "....kTtttttt",
      "....kTtkkktt",
      "....kTtwkktt",
      "....kTtttttt",
      "....kTtttttT",
      "....kTtttttT",
      ".....kTttttt",
      ".....kTtttff",
      "......kTtttt",
      ".......kTttt",
      "........kTTt",
      ".........kTT",
      ".........kTt",
      "....kkkkkWWW",
      "..kkssSkWWWW",
      ".ksssSSSkWWW",
      ".kssSSSSkWWy",
      "ksssSSSSSkWW",
      "ksssSSSSSkWW",
      "ksdsSSSSSskW",
      "ksdssSSSSskW",
      "ksdssSSSSSkW",
      "ksdsssSSSSkW",
      "kkkkkkkkkkkk"] },
    hair_short: { group:"portraits", sym:true, note:"Hair overlay, drawn over a portrait base. Hair Z, shine X.", pal:{"Z": "#5a3a22", "X": "#8a5c34", "t": "#e8c8a8", "T": "#c49a78"},
      rows:["............",
      "........kkkk",
      "......kkZZZZ",
      ".....kZZZZZZ",
      "....kZZZXZZZ",
      "....kZZZZZXZ",
      "....kZZXZZZZ",
      "....kZk.....",
      "....kZ......",
      "....k.......",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............"] },
    hair_slick: { group:"portraits", sym:true, note:"Hair overlay, drawn over a portrait base. Hair Z, shine X.", pal:{"Z": "#5a3a22", "X": "#8a5c34", "t": "#e8c8a8", "T": "#c49a78"},
      rows:["............",
      "........kkkk",
      "......kkZZZZ",
      ".....kZZZZXX",
      "....kZZZZZXZ",
      "....kZZZZZZk",
      "....kZZkk...",
      "....kZk.....",
      "....kk......",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............"] },
    hair_bob: { group:"portraits", sym:true, note:"Hair overlay, drawn over a portrait base. Hair Z, shine X.", pal:{"Z": "#5a3a22", "X": "#8a5c34", "t": "#e8c8a8", "T": "#c49a78"},
      rows:["............",
      "........kkkk",
      "......kkZZZZ",
      ".....kZZZZZZ",
      "....kZZZZXZZ",
      "...kZZZZZZZZ",
      "...kZZXZZZZZ",
      "..kZZZZXZZZZ",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZZk.....",
      "...kkk......",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............"] },
    hair_long: { group:"portraits", sym:true, note:"Hair overlay, drawn over a portrait base. Hair Z, shine X.", pal:{"Z": "#5a3a22", "X": "#8a5c34", "t": "#e8c8a8", "T": "#c49a78"},
      rows:["............",
      "........kkkk",
      "......kkZZZZ",
      ".....kZZZZZZ",
      "....kZZZZXZZ",
      "...kZZZZZZZZ",
      "...kZZXZZZZZ",
      "..kZZZZXZZZZ",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZk......",
      "..kZZZk.....",
      "...kkk......",
      "............",
      "............",
      "............",
      "............",
      "............"] },
    moustache: { group:"portraits", sym:true, note:"Hair overlay, drawn over a portrait base. Hair Z, shine X.", pal:{"Z": "#5a3a22", "X": "#8a5c34", "t": "#e8c8a8", "T": "#c49a78"},
      rows:["............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      ".........kZZ",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "............"] },
    nasf_down: { group:"carl", note:"Nasaro (woman): hair Z below the helmet.", pal:{"Z": "#5a3a22", "X": "#8a5c34"},
      rows:["......kkkk......",
      "....kkoOOokk....",
      "...koOkkkkOok...",
      "...kokeEEekok...",
      "..koOkeEEekOok..",
      "..kookeeeekook..",
      "...kookkkkook...",
      "...ZkkMMMMkkZ...",
      "...ZsSSssSSsZ...",
      "..ksSSsyysSSsk..",
      "..ksdssssssdsk..",
      "..kOksssssskOk..",
      "...ksssddsssk...",
      "...kssk..kssk...",
      "...kdNk..kNdk...",
      "...kkkk..kkkk..."] },
    nasf_down1: { group:"carl", note:"", pal:{"Z": "#5a3a22", "X": "#8a5c34"},
      rows:["......kkkk......",
      "....kkoOOokk....",
      "...koOkkkkOok...",
      "...kokeEEekok...",
      "..koOkeEEekOok..",
      "..kookeeeekook..",
      "...kookkkkook...",
      "...ZkkMMMMkkZ...",
      "...ZsSSssSSsZ...",
      "..ksSSsyysSSsk..",
      "..ksdssssssdsk..",
      "..kOksssssskOk..",
      "...ksssddsssk...",
      "...kssk..kssk...",
      "...kkkk..kdNk...",
      "..........kkkk.."] },
    nasf_up: { group:"carl", note:"", pal:{"Z": "#5a3a22", "X": "#8a5c34"},
      rows:["......kkkk......",
      "....kkoOOokk....",
      "...koOOooOOok...",
      "...kooooooook...",
      "..koOooooooOok..",
      "..kooooooooook..",
      "...kookkkkook...",
      "....kkZMMZkk....",
      "...ksSkZZkSsk...",
      "..ksSSkZZkSSsk..",
      "..ksdskyyksdsk..",
      "..kOksskksskOk..",
      "...ksssddsssk...",
      "...kssk..kssk...",
      "...kdNk..kNdk...",
      "...kkkk..kkkk..."] },
    nasf_up1: { group:"carl", note:"", pal:{"Z": "#5a3a22", "X": "#8a5c34"},
      rows:["......kkkk......",
      "....kkoOOokk....",
      "...koOOooOOok...",
      "...kooooooook...",
      "..koOooooooOok..",
      "..kooooooooook..",
      "...kookkkkook...",
      "....kkZMMZkk....",
      "...ksSkZZkSsk...",
      "..ksSSkZZkSSsk..",
      "..ksdskyyksdsk..",
      "..kOksskksskOk..",
      "...ksssddsssk...",
      "...kssk..kssk...",
      "...kkkk..kdNk...",
      "..........kkkk.."] },
    nasf_side: { group:"carl", note:"", pal:{"Z": "#5a3a22", "X": "#8a5c34"},
      rows:["......kkkk......",
      ".....kooOOkk....",
      "....koOOkkkOk...",
      "....kooOkeEEk...",
      "...kooookeEEEk..",
      "...kooookeeek...",
      "...Zkkookkkk....",
      "...ZZkMMMk......",
      "...ZZysSSsk.....",
      "...ZyysSSSsk....",
      "...kyysdssk.....",
      "....kksssOk.....",
      ".....ksssk......",
      ".....ksssk......",
      ".....kdkNk......",
      ".....kkkkk......"] },
    nasf_side1: { group:"carl", note:"", pal:{"Z": "#5a3a22", "X": "#8a5c34"},
      rows:["......kkkk......",
      ".....kooOOkk....",
      "....koOOkkkOk...",
      "....kooOkeEEk...",
      "...kooookeEEEk..",
      "...kooookeeek...",
      "...Zkkookkkk....",
      "...ZZkMMMk......",
      "...ZZysSSsk.....",
      "...ZyysSSSsk....",
      "...kyysdssk.....",
      "....kksssOk.....",
      ".....ksssk......",
      "....ksk.ksk.....",
      "...kdk...kNk....",
      "...kkk...kkk...."] }
  };

  var ANIM = {"nasf": {"down": ["nasf_down", "nasf_down1", "nasf_down", "nasf_down1|flip"], "up": ["nasf_up", "nasf_up1", "nasf_up", "nasf_up1|flip"], "right": ["nasf_side", "nasf_side1"], "left": ["nasf_side|flip", "nasf_side1|flip"]}, "carl": {"down": ["carl_down", "carl_down1", "carl_down", "carl_down1|flip"], "up": ["carl_up", "carl_up1", "carl_up", "carl_up1|flip"], "right": ["carl_side", "carl_side1"], "left": ["carl_side|flip", "carl_side1|flip"]}, "haemen": {"down": ["haemen_down"], "up": ["haemen_up"], "right": ["haemen_side"], "left": ["haemen_side|flip"]}, "otterlin": {"down": ["otterlin_down"], "up": ["otterlin_down"], "right": ["otterlin_side", "otterlin_side1"], "left": ["otterlin_side|flip", "otterlin_side1|flip"]}, "verdanix": {"down": ["verdanix_down"], "up": ["verdanix_down"], "right": ["verdanix_side", "verdanix_side1"], "left": ["verdanix_side|flip", "verdanix_side1|flip"]}, "aetherwing": {"down": ["aetherwing", "aetherwing1"], "up": ["aetherwing", "aetherwing1"], "right": ["aetherwing", "aetherwing1"], "left": ["aetherwing", "aetherwing1"]}, "volcanut": {"down": ["volcanut_down"], "up": ["volcanut_down"], "right": ["volcanut_side", "volcanut_side1"], "left": ["volcanut_side|flip", "volcanut_side1|flip"]}, "water": {"any": ["water", "water1"]}, "astralite": {"any": ["astralite", "astralite1"]}};

  // ── Studio edits: the Art Studio saves edited sprites here, and the game
  //    uses them in this browser until they're exported into this file. ──
  var OVERRIDE_KEY = 'aov.art.overrides';
  var overrides = {};
  try { overrides = JSON.parse(localStorage.getItem(OVERRIDE_KEY) || '{}') || {}; } catch(e){}

  function def(name){
    var d = SPRITES[name]; if (!d) return null;
    var o = overrides[name];
    if (o) return { group:d.group, note:d.note, rows:o.rows, pal:o.pal || d.pal, sym:false, edited:true };
    return d;
  }
  // full rows (mirror applied)
  function rows(name){
    var d = def(name); if (!d) return null;
    return d.sym ? d.rows.map(function(r){ return r + r.split('').reverse().join(''); }) : d.rows.slice();
  }
  function colour(name, ch){
    var d = def(name);
    var o = overrides.__palette || {};
    return (d && d.pal && d.pal[ch]) || o[ch] || PALETTE[ch] || null;
  }
  var cache = {};
  // A registered recolour turns one sprite into another world's version of it:
  // canvas('grass@yvoris') draws grass with Yvoris's palette.
  var RECOLOURS = {};
  function recolour(id, map){ RECOLOURS[id] = map; cache = {}; urls = {}; }
  function canvas(spec){
    // spec: "name", "name|flip", "name@recolour" or "name@recolour|flip"
    if (cache[spec]) return cache[spec];
    var parts = spec.split('|'), flip = parts[1] === 'flip', nm = parts[0].split('@'), name = nm[0], rc = nm[1] ? RECOLOURS[nm[1]] || {} : null;
    var r = rows(name); if (!r) return null;
    var c = document.createElement('canvas'); c.width = r[0].length; c.height = r.length;
    var g = c.getContext('2d');
    for (var y = 0; y < r.length; y++) for (var x = 0; x < r[y].length; x++) {
      var ch = r[y][x]; if (ch === '.') continue;
      var col = (rc && rc[ch]) || colour(name, ch); if (!col) continue;
      g.fillStyle = col; g.fillRect(flip ? r[y].length - 1 - x : x, y, 1, 1);
    }
    cache[spec] = c;
    return c;
  }
  // draw a sprite with its bottom-centre at (x, y), scaled by s
  function draw(ctx, spec, x, y, s, alpha){
    var c = canvas(spec); if (!c) return;
    var prev = ctx.imageSmoothingEnabled; ctx.imageSmoothingEnabled = false;
    if (alpha != null) { ctx.save(); ctx.globalAlpha = alpha; }
    ctx.drawImage(c, Math.round(x - c.width * s / 2), Math.round(y - c.height * s), c.width * s, c.height * s);
    if (alpha != null) ctx.restore();
    ctx.imageSmoothingEnabled = prev;
  }
  // a scaled-up PNG data URL (for cards, encounter screens, DOM use)
  var urls = {};
  function url(spec, scale){
    var key = spec + '@' + (scale || 8);
    if (urls[key]) return urls[key];
    var c = canvas(spec); if (!c) return '';
    var s = scale || 8, o = document.createElement('canvas'); o.width = c.width * s; o.height = c.height * s;
    var g = o.getContext('2d'); g.imageSmoothingEnabled = false; g.drawImage(c, 0, 0, o.width, o.height);
    return (urls[key] = o.toDataURL('image/png'));
  }
  function frame(set, dir, n){
    var a = ANIM[set]; if (!a) return set;
    var list = a[dir] || a.any || a.down;
    return list[(n | 0) % list.length];
  }
  function saveOverride(name, data){
    if (name === '__palette') overrides.__palette = data; else overrides[name] = data;
    try { localStorage.setItem(OVERRIDE_KEY, JSON.stringify(overrides)); } catch(e){}
    cache = {}; urls = {};
  }
  function clearOverride(name){
    if (name) delete overrides[name]; else overrides = {};
    try { localStorage.setItem(OVERRIDE_KEY, JSON.stringify(overrides)); } catch(e){}
    cache = {}; urls = {};
  }

  window.AOV_ART = {
    PALETTE:PALETTE, SPRITES:SPRITES, ANIM:ANIM,
    names:function(){ return Object.keys(SPRITES); },
    def:def, rows:rows, colour:colour, canvas:canvas, draw:draw, url:url, frame:frame, recolour:recolour,
    overrides:function(){ return overrides; }, saveOverride:saveOverride, clearOverride:clearOverride
  };
})();
