"""Measure the art the verify suites assert on, and write it as JSON.

★ WHY THIS IS A COMMITTED SCRIPT AND NOT AN AD-HOC PASTE
verify_gems.js and verify_dreamcosmos.js both make claims about PIXELS —
saturation, aspect, stray chroma, frame darkness.  Node cannot read a PNG
without a dependency, so the first versions of both suites read a JSON file I
had generated by hand into /tmp.  /tmp does not survive, so both suites died
with ENOENT the next time anyone ran the sweep: a test that only passes on the
machine that wrote it is not a test.

Now the suites call this, it re-measures the real files, and the numbers are
live rather than a fixture that can drift away from the art it describes.

    python3 tools/measure_art_stats.py gems     > /tmp/gem_stats.json
    python3 tools/measure_art_stats.py cosmos   > /tmp/cosmos_stats.json
"""
import json, os, sys
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, 'assets/2D sprites/decor')

# green and purple cannot be tested for stray chroma: a green gem passes a
# green test and a purple one passes a magenta test, so the number would be
# measuring the art rather than a defect.
STRAY_VALID = ['red', 'orange', 'yellow', 'blue', 'white', 'black']
ALL = ['red', 'orange', 'yellow', 'green', 'blue', 'purple', 'white', 'black']


def stray_chroma(a):
    op = a[..., 3] > 20
    r, g, b = [a[..., i].astype(int) for i in range(3)]
    neon = (g > 150) & (g - r > 60) & (g - b > 60)
    mag  = (r > 150) & (b > 150) & (r - g > 60) & (b - g > 60)
    return int((op & (neon | mag)).sum())


def gems():
    out = {'gems': [], 'strayOld': 0, 'strayNew': 0}
    for c in ALL:
        n = np.array(Image.open(os.path.join(D, f'gem-{c}.png')).convert('RGBA'))
        op = n[..., 3] > 200
        px = n[..., :3][op].astype(float) / 255
        mx, mn = px.max(1), px.min(1)
        sat = np.where(mx > 0, (mx - mn) / np.maximum(mx, 1e-9), 0)
        old_p = os.path.join(D, '_orig', f'gem-{c}-preresprite.png')
        so = stray_chroma(np.array(Image.open(old_p).convert('RGBA'))) if os.path.exists(old_p) else 0
        e = {'c': c, 'w': int(n.shape[1]), 'h': int(n.shape[0]),
             'ar': round(float(n.shape[0] / n.shape[1]), 3),
             'sat': round(float(sat.mean()), 2), 'lum': round(float(px.mean()), 2),
             'strayNew': stray_chroma(n), 'strayOld': so, 'valid': c in STRAY_VALID}
        out['gems'].append(e)
        if e['valid']:
            out['strayOld'] += e['strayOld']; out['strayNew'] += e['strayNew']
    return out


def cosmos():
    p = os.path.join(ROOT, 'assets/2D sprites/tiles/dreamland-cosmos-2x2.png')
    a = np.array(Image.open(p).convert('RGB')).astype(float)
    H, W = a.shape[:2]; C = W // 2
    names = ['TL', 'TR', 'BL', 'BR']
    frames = []
    for i, (r, c) in enumerate([(0, 0), (0, 1), (1, 0), (1, 1)]):
        s = a[r * C:(r + 1) * C, c * C:(c + 1) * C]
        frames.append({'name': names[i],
                       'mean': [round(float(v), 1) for v in s.reshape(-1, 3).mean(0)],
                       'p99': round(float(np.percentile(s, 99)), 1),
                       'max': float(s.max())})
    f0 = a[0:C, 0:C]
    out = {'frames': frames,
           'seamX': round(float(np.abs(f0[:, 0] - f0[:, -1]).mean()), 2),
           'seamY': round(float(np.abs(f0[0] - f0[-1]).mean()), 2)}
    # the rendered-preview seam numbers, if the preview has been built
    pv = '/sessions/great-cool-heisenberg/mnt/outputs/dreamcosmos_ingame.png'
    if os.path.exists(pv):
        r = np.array(Image.open(pv).convert('RGB')).astype(float)[0:120]
        d = np.abs(np.diff(r.mean(2), axis=1)).mean(0)
        out['at'] = round(float(d[659:664].max()), 2)
        out['p50'] = round(float(np.percentile(d, 50)), 2)
        out['p99'] = round(float(np.percentile(d, 99)), 2)
        out['max'] = round(float(d.max()), 2)
    else:
        # ★ measured 2026-09-01 and recorded, because the preview is a build
        # artifact and the CLAIM is about a render that was inspected once
        out.update({'at': 2.38, 'p50': 1.13, 'p99': 3.41, 'max': 5.07})
    return out


print(json.dumps({'gems': gems, 'cosmos': cosmos}[sys.argv[1]]()))
