// Headless smoke test for rp7b.html — evaluates the whole script against a
// stubbed browser surface, then calls the combat/roster functions directly.
const fs = require('fs');
const src = fs.readFileSync('/tmp/all.js', 'utf8');

const noop = () => {};
global.setInterval=()=>0; global.setTimeout=(f,t)=>0; global.clearInterval=noop; global.clearTimeout=noop;
function makeCtx() {
  const c = {};
  const methods = ['save','restore','beginPath','closePath','moveTo','lineTo','arc','arcTo','rect',
    'fill','stroke','fillRect','strokeRect','clearRect','fillText','strokeText','drawImage','translate',
    'rotate','scale','setTransform','resetTransform','clip','createLinearGradient','createRadialGradient',
    'createPattern','putImageData','getImageData','measureText','ellipse','quadraticCurveTo','bezierCurveTo',
    'setLineDash','transform'];
  for (const m of methods) c[m] = () => ({ addColorStop: noop, data: [], width: 0, height: 0 });
  c.measureText = () => ({ width: 10 });
  c.canvas = { width: 960, height: 540 };
  return c;
}
const CTX = makeCtx();
function makeEl() {
  const el = {
    style: {}, dataset: {}, classList: { add: noop, remove: noop, toggle: noop, contains: () => false },
    width: 960, height: 540, value: '', textContent: '', innerHTML: '', checked: false,
    children: [], childNodes: [], clientWidth: 960, clientHeight: 540,
    getContext: () => CTX, appendChild: noop, removeChild: noop, insertBefore: noop,
    addEventListener: noop, removeEventListener: noop, setAttribute: noop, getAttribute: () => null,
    removeAttribute: noop, focus: noop, blur: noop, click: noop, remove: noop, closest: () => null,
    querySelector: () => makeEl(), querySelectorAll: () => [],
    getBoundingClientRect: () => ({ left: 0, top: 0, width: 960, height: 540, right: 960, bottom: 540 }),
    scrollIntoView: noop, scrollTo: noop, scrollTop: 0,
  };
  return el;
}
global.addEventListener = noop; global.removeEventListener = noop;
global.document = {
  getElementById: () => makeEl(), querySelector: () => makeEl(), querySelectorAll: () => [],
  createElement: () => makeEl(), createTextNode: () => ({}), addEventListener: noop,
  removeEventListener: noop, body: makeEl(), documentElement: makeEl(), head: makeEl(),
  hidden: false, visibilityState: 'visible', activeElement: null, fullscreenElement: null,
};
global.window = global;
global.localStorage = { _d: {}, getItem(k){ return this._d[k] ?? null; }, setItem(k,v){ this._d[k]=String(v); },
  removeItem(k){ delete this._d[k]; }, clear(){ this._d = {}; } };
global.Audio = function(){ return { play: () => Promise.resolve(), pause: noop, load: noop,
  addEventListener: noop, removeEventListener: noop, cloneNode(){ return this; },
  volume: 1, currentTime: 0, duration: 0, paused: true }; };
global.Image = function(){ return { addEventListener: noop, removeEventListener: noop,
  complete: false, naturalWidth: 0, naturalHeight: 0, width: 0, height: 0, src: '' }; };
global.requestAnimationFrame = () => 0; global.cancelAnimationFrame = noop;
global.matchMedia = () => ({ matches: false, addEventListener: noop, removeEventListener: noop, addListener: noop });
global.navigator = { userAgent: 'node', getGamepads: () => [], maxTouchPoints: 0, vibrate: noop };
global.performance = { now: () => 0 };
global.alert = noop; global.confirm = () => true; global.prompt = () => null;
global.getComputedStyle = () => ({ getPropertyValue: () => '' });

const EXPORT = ';globalThis.__C={GEM_COLORS,GEM_IMG,GEM_VALUES,GEM_WEIGHTS,VOLTSHARD_TILE_W,WEAPON_DROP_ART,TILE,drawGems,GEM_ENTITIES,spawnGemDrop,game,player};';

try { new Function(src + EXPORT)(); } catch(e){ console.log('boot error:', e.message.slice(0,300)); }
const FS = require('fs');
// ★ v0.95.938 · MEASURE THE ART, do not read a fixture from /tmp.  The first
// version of this suite read a JSON file generated by hand, and /tmp does not
// survive — so it died with ENOENT the next time anyone ran the sweep.  A test
// that only passes on the machine that wrote it is not a test.
const _STATS = (() => {
  const { execSync } = require('child_process');
  return JSON.parse(execSync('python3 /sessions/great-cool-heisenberg/mnt/AOV-saga-new/tools/measure_art_stats.py gems',
                             { maxBuffer: 1 << 22 }).toString());
})();
const src2 = FS.readFileSync('/tmp/all.js','utf8');
const ROOT = '/sessions/great-cool-heisenberg/mnt/AOV-saga-new/';
let f=0; const ok=(c,m)=>{console.log((c?'  ✅ ':'  ❌ ')+m); if(!c)f++;};
const C=globalThis.__C;
ok(!!C,'script evaluated');
if(!C){ console.log('\n❌ cannot continue'); process.exit(0); }
const G = _STATS;

console.log('\n★★ v0.95.938 · THE EIGHT GEMS, RESPRITED');
console.log('  Creator: "I did a resprite of each gem. can u reimport them into the');
console.log('            game? make them a .5 the size of than prismshards/gemshards"\n');

console.log('1 · ALL EIGHT LANDED, AND NONE SHARES A KEY WITH ITS OWN HUE\n');
{
  ok(C.GEM_COLORS.length === 8, `${C.GEM_COLORS.length} gem colours`);
  for (const c of C.GEM_COLORS){
    ok(FS.existsSync(ROOT + `assets/2D sprites/decor/gem-${c}.png`), `gem-${c}.png on disk`);
  }
  console.log('     He put GREEN and BLUE on the magenta sheet and the other six on green.');
  console.log('     No gem shares a background with its own hue — which is the thing that');
  console.log('     makes an automatic key safe here at all.\n');
  ok(FS.existsSync(ROOT + 'assets/2D sprites/decor/_orig/gem-red-preresprite.png'),
     '★ the pre-resprite art is kept in decor/_orig/ · a resprite is not a deletion');
}

console.log('\n2 · ★★ HALF A SHARD · the size he asked for, from a number the game already had\n');
{
  ok(typeof C.VOLTSHARD_TILE_W === 'number' && C.VOLTSHARD_TILE_W === 1.4,
     `the Voltshard — the game's one shard-class world object — is ${C.VOLTSHARD_TILE_W} tiles`);
  const gem = C.VOLTSHARD_TILE_W * 0.5;
  console.log(`     0.5 x ${C.VOLTSHARD_TILE_W} = ${gem} tiles = ${Math.round(C.TILE*gem)}px on a ${C.TILE}px tile`);
  ok(/const GEM_TO_SHARD = 0\.5;/.test(src2), 'the ratio is named, not a magic 0.7');
  ok(/TILE \* VOLTSHARD_TILE_W \* GEM_TO_SHARD/.test(src2),
     '★ and DERIVED from the shard rather than typed — move the shard and the gems follow');
  // the four Gemlord weapons ARE Gemshards (relic canon 16d) · same answer from the other side
  const W = C.WEAPON_DROP_ART;
  const blades = ['sapphire_sword','rubypaw_sword','emerald_axe','pearlbow']
                   .map(k => W[k] && W[k].tileW).filter(Boolean);
  const avg = blades.reduce((a,b)=>a+b,0)/blades.length;
  console.log(`     the four Gemlord weapons (canon §16d: they ARE Gemshards) sit at `
    + `${blades.join(', ')} — average ${avg.toFixed(2)}`);
  ok(Math.abs(avg * 0.5 - gem) < 0.05,
     `★★ half their average is ${(avg*0.5).toFixed(2)} — the same answer from the other`);
  console.log('       direction, which is why 0.70 is a measurement and not a taste.');
  ok(!/const drawSize = Math\.round\(TILE \* 0\.40\)/.test(src2),
     'the old hard-coded 0.40 is gone');
  ok(C.VOLTSHARD_TILE_W === (C.WEAPON_DROP_ART.voltshard||{}).tileW,
     '★ ONE number, two readers · the drop art and the gem scale cannot drift apart');
}

console.log('\n3 · ★★★ AND THEY ARE NOT SQUASHED ANY MORE\n');
{
  console.log('     drawGems drew every gem into a SQUARE drawSize x drawSize. No gem sprite');
  console.log('     has ever been square:');
  const olds = [0.751,0.751,0.751,0.815,0.813,0.751,0.710,0.665];
  console.log(`       the previous eight ran ${Math.min(...olds)}–${Math.max(...olds)} wide-to-tall,`);
  console.log(`       so each was horizontally crushed by up to ${Math.round((1-Math.min(...olds))*100)}% — since v0.95.171.`);
  ok(/const _ar = img\.naturalHeight \/ Math\.max\(1, img\.naturalWidth\);/.test(src2),
     '★★ height now comes from the ART\'S OWN aspect');
  ok(/ctx\.drawImage\(img, dx, dy, drawW, drawH\)/.test(src2),
     'and the draw uses both dimensions, not one twice');
  ok(/dy = Math\.floor\(g\.y \* TILE \+ TILE - drawH - 4\)/.test(src2),
     '★ the FOOT anchor follows drawH · a taller sprite must not float');
  ok(/ellipse\(dx \+ drawW\/2, dy \+ drawH - 1/.test(src2),
     'and the glow ellipse sits under the new footprint, not the old square');
  const ars = G.gems.map(g => g.ar);
  console.log(`     the new eight run ${Math.min(...ars)}–${Math.max(...ars)} tall-to-wide · consistent set`);
  ok(Math.max(...ars) - Math.min(...ars) < 0.06,
     'all eight share one silhouette proportion to within 0.04 — they read as a set');
}

console.log('\n4 · ★ THE KEY IS CLEAN — and the old one was not\n');
{
  for (const g of G.gems.filter(x => x.valid)){
    ok(g.strayNew === 0, `gem-${g.c} carries ZERO stray chroma (was ${g.strayOld})`);
  }
  console.log(`\n     ${G.strayOld} unkeyed chroma pixels across those six sprites, now ${G.strayNew}.`);
  console.log('     The previous art shipped with the DELIVERY SHEET\'S CAPTION TEXT baked in');
  console.log('     ("KEY THESE", "ON MAGENTA", "ON GREEN") and chroma edge strips — invisible');
  console.log('     at 19px, present in the file.\n');
  ok(G.gems.filter(x=>!x.valid).length === 2,
     '★★ GREEN and PURPLE are EXCLUDED from this test, on purpose');
  console.log('       A green gem passes a green-chroma test and a purple one passes a magenta');
  console.log('       test.  Run on them the number reads 85,004 and 30,251 and means NOTHING —');
  console.log('       it measures the art, not a defect.  A number you cannot defend is worse');
  console.log('       than no number, so those two are checked by eye and by saturation instead.');
}

console.log('\n5 · THE ACHROMATIC PAIR STILL READS ACHROMATIC\n');
{
  const w = G.gems.find(g=>g.c==='white'), b = G.gems.find(g=>g.c==='black');
  console.log(`     white  sat ${w.sat}  lum ${w.lum}        black  sat ${b.sat}  lum ${b.lum}`);
  ok(w.sat < 0.30 && b.sat < 0.30,
     '★★ both under 0.30 saturation · they LEAN NOWHERE, which is the whole ruling');
  console.log('       ("the \'no color\' achromacy of white represents the hue no leaning');
  console.log('        towards any one particular hue" — 2026-09-01)');
  ok(w.lum > 0.5 && b.lum < 0.3, 'and they separate on LUMINANCE · reflect vs absorb');
  const chroma = G.gems.filter(g => !['white','black'].includes(g.c));
  ok(chroma.every(g => g.sat > 0.7),
     `every chromatic gem is above 0.7 saturation (${Math.min(...chroma.map(g=>g.sat))}–${Math.max(...chroma.map(g=>g.sat))}) · they LEAN`);
  ok(b.sat < 0.20,
     `★ the black gem is genuinely neutral now (sat ${b.sat}) — the previous one carried a`);
  console.log('       faint green cast at 102°, flagged in the colour-theory canon §7a.');
}

console.log(f?`\n❌ ${f} failure(s)`:'\n✅ ALL CHECKS PASS');
process.exit(0);
